export type Exhibit = {
  id: string;
  slug: string;
  wikiTitle: string;
  year: string;
  sortYear: number;
  title: string;
  subtitle: string;
  blurb: string;
  tags: string[];
  image: string;
  feature?: boolean;
  span?: 2;
};

const img = (file: string) => `assets/wiki/${file}`;

const exhibitData: Exhibit[] = [
  {
    id: "hubot",
    slug: "hubot",
    wikiTitle: "Hubot",
    year: "c.1983",
    sortYear: 1983,
    title: "Hubot",
    subtitle: "The butler robot with an Atari inside",
    blurb:
      "A 50kg wheeled companion with a CP/M computer, a voice synthesizer, an Atari 2600, and a Polaroid sonar head. Priced at $3,495, it scanned rooms, spoke 1,200 words, and played Defender.",
    tags: ["Robot", "Voice", "Home Computer"],
    image: img("hubot-hardware.webp"),
    feature: true,
  },
  {
    id: "power-glove",
    slug: "nintendo-power-glove",
    wikiTitle: "Nintendo Power Glove",
    year: "1989",
    sortYear: 1989,
    title: "Power Glove",
    subtitle: "A $10,000 NASA glove, shrunk to $90",
    blurb:
      "Mattel had nine months to turn VPL's research-grade DataGlove into a toy. It sold 1.3 million units. \"I love the Power Glove. It's so bad.\"",
    tags: ["Gesture", "Gaming", "Wearable"],
    image: img("power-glove-1.jpg"),
    span: 2,
  },
  {
    id: "atari-mindlink",
    slug: "atari-mindlink",
    wikiTitle: "Atari Mindlink",
    year: "1984",
    sortYear: 1984,
    title: "Atari Mindlink",
    subtitle: "Mind control (actually eyebrow control)",
    blurb:
      "A headband that read forehead muscle tension and called it telepathy. Demoed at CES, then canceled. Testers got headaches from wiggling their brows.",
    tags: ["BCI", "Biofeedback", "Vaporware"],
    image: img("atari-mindlink-2.jpg"),
  },
  {
    id: "videoplace",
    slug: "videoplace",
    wikiTitle: "VIDEOPLACE / Artificial Reality",
    year: "1970s–80s",
    sortYear: 1978,
    title: "VIDEOPLACE",
    subtitle: "Artificial reality without goggles",
    blurb:
      "Myron Krueger put people in shared silhouette worlds using only cameras and projectors. No headsets, no gloves — just your body, glowing on screen.",
    tags: ["Gesture", "Computer Vision", "Art"],
    image: img("videoplace-mediaartnet.jpg"),
  },
  {
    id: "p300-speller",
    slug: "p300-speller",
    wikiTitle: "The P300 Speller",
    year: "1988",
    sortYear: 1988,
    title: "P300 Speller",
    subtitle: "Talking off the top of your head",
    blurb:
      "The first BCI that let you type with brainwaves alone. Focus on a letter in a 6×6 grid; the system reads the P300 spike when your target flashes. 95% accuracy at 12 bits/min.",
    tags: ["Brain Control", "BCI", "EEG"],
    image: img("p300-rowcolumn.webp"),
  },
  {
    id: "vpl",
    slug: "vpl-research",
    wikiTitle: "VPL Research EyePhone & DataGlove",
    year: "1980s",
    sortYear: 1985,
    title: "VPL EyePhone & DataGlove",
    subtitle: "The birth of commercial VR",
    blurb:
      "Jaron Lanier's fiber-optic glove and Fresnel-lens headset defined the visual language of virtual reality. A full system cost $250,000 and ran at 5 fps.",
    tags: ["VR", "Gesture", "Wearables"],
    image: img("vpl-eyephone-demo.jpg"),
    span: 2,
  },
  {
    id: "virtuality",
    slug: "virtuality",
    wikiTitle: "Virtuality Arcade VR System",
    year: "1990",
    sortYear: 1990,
    title: "Virtuality",
    subtitle: "Networked VR in an arcade pod",
    blurb:
      "Amiga 3000s, camcorder LCDs, and magnetic tracking. Dactyl Nightmare let four players fight in cyberspace years before Doom.",
    tags: ["VR", "Arcade", "Multiplayer"],
    image: img("virtuality-1000cs-1.jpg"),
  },
  {
    id: "eyetap",
    slug: "eyetap",
    wikiTitle: "Steve Mann’s EyeTap / Wearable Computing",
    year: "1980s",
    sortYear: 1985,
    title: "EyeTap",
    subtitle: "Wearable computing before it had a name",
    blurb:
      "Steve Mann built camera-display eyeglasses in high school. The computer mediates reality itself — not a HUD, but a reversible eye.",
    tags: ["Wearable", "AR", "Sousveillance"],
    image: img("eyetap-mann-glass-2.jpg"),
  },
  {
    id: "digital-desk",
    slug: "digital-desk",
    wikiTitle: "The Digital Desk",
    year: "1991",
    sortYear: 1991,
    title: "The Digital Desk",
    subtitle: "Paper meets projector",
    blurb:
      "Pierre Wellner pointed a camera and projector at an ordinary desk. Point at printed numbers; the desk calculates and projects the answer onto the paper.",
    tags: ["Tangible", "AR", "Projection"],
    image: img("digital-desk-2.jpg"),
  },
  {
    id: "mandala",
    slug: "mandala",
    wikiTitle: "Mandala / The Vivid Group Gesture VR System",
    year: "1986",
    sortYear: 1986,
    title: "Mandala",
    subtitle: "Full-body VR on an Amiga",
    blurb:
      "The Vivid Group put your live video silhouette inside a virtual world. Punch objects, play drums, dance — 30fps, no controller, on an Amiga 1000.",
    tags: ["Gesture", "VR", "Computer Vision"],
    image: img("mandala-siggraph-1.jpg"),
  },
  {
    id: "put-that-there",
    slug: "put-that-there",
    wikiTitle: "Put-That-There",
    year: "1980",
    sortYear: 1980,
    title: "Put-That-There",
    subtitle: "Voice + gesture at the graphics interface",
    blurb:
      "MIT's Architecture Machine Group let you move shapes by speaking and pointing. It asked clarifying questions when it couldn't understand you.",
    tags: ["Voice", "Gesture", "Multimodal"],
    image: img("put-that-there-video.jpg"),
  },
  {
    id: "speak-spell",
    slug: "speak-spell",
    wikiTitle: "Texas Instruments Speak & Spell",
    year: "1978",
    sortYear: 1978,
    title: "Speak & Spell",
    subtitle: "The first talking chip",
    blurb:
      "Texas Instruments put a 10th-order LPC vocal tract model on a single chip. It taught kids to spell, became an IEEE Milestone, and soundtracked Kraftwerk.",
    tags: ["Voice", "Speech Synthesis", "Toy"],
    image: img("speak-spell-1.jpg"),
  },
  {
    id: "kurzweil",
    slug: "kurzweil-reading-machine",
    wikiTitle: "Kurzweil Reading Machine",
    year: "1976",
    sortYear: 1976,
    title: "Kurzweil Reading Machine",
    subtitle: "Print made audible for the blind",
    blurb:
      "The first omni-font OCR plus a CCD scanner plus a speech synthesizer. Walter Cronkite read his sign-off with it. Stevie Wonder took the first unit home.",
    tags: ["Accessibility", "OCR", "Text-to-Speech"],
    image: img("kurzweil-reading-machine-1.jpg"),
  },
  {
    id: "active-badge",
    slug: "active-badge",
    wikiTitle: "Olivetti Active Badge",
    year: "1992",
    sortYear: 1992,
    title: "Active Badge",
    subtitle: "Your location, broadcast every 10 seconds",
    blurb:
      "Olivetti Research made an IR badge that told the building where you were. Phones followed you. Desktops moved with you. Privacy was born as a question.",
    tags: ["Wearable", "Location-Aware", "Ubicomp"],
    image: img("active-badge-1.gif"),
  },
  {
    id: "twiddler",
    slug: "twiddler",
    wikiTitle: "Handykey Twiddler Chord Keyboard",
    year: "1992",
    sortYear: 1992,
    title: "Twiddler",
    subtitle: "A keyboard in one hand",
    blurb:
      "A chording keypad you hold like a grenade. MIT wearable researchers typed 60 wpm while walking. Still in production 33 years later.",
    tags: ["Input", "Chorded", "One-Handed"],
    image: img("twiddler-original-1.png"),
  },
  {
    id: "gridpad-100",
    slug: "gridpad-100",
    wikiTitle: "GRiDPad 100",
    year: "1989",
    sortYear: 1989,
    title: "GRiDPad 100",
    subtitle: "First commercial tablet computer with pen input.",
    blurb: "Pioneered portable form-factor handwriting recognition and stylus-driven UI on MS-DOS.",
    tags: ["pen computing", "handwriting recognition", "tablet PC"],
    image: img("gridpad-100-1.jpg"),
  },
  {
    id: "heathkit-hero-1",
    slug: "heathkit-hero-1",
    wikiTitle: "Heathkit HERO 1",
    year: "1982",
    sortYear: 1982,
    title: "Heathkit HERO 1",
    subtitle: "Educational robot with sonar, light, and sound sensors.",
    blurb: "Brought programmable physical-world sensing and locomotion to hobbyist HCI experiments.",
    tags: ["Educational Robot", "Programmable Sensing", "Human-Computer Interaction"],
    image: img("heathkit-hero-1-1.jpg"),
  },
  {
    id: "hp-150-touchscreen",
    slug: "hp-150-touchscreen",
    wikiTitle: "HP-150 Touchscreen",
    year: "1983",
    sortYear: 1983,
    title: "HP-150 Touchscreen",
    subtitle: "CRT monitor with infrared touch overlay for office PCs.",
    blurb: "First mass-market computer to ship with direct finger touch as primary input.",
    tags: ["Touchscreen", "Infrared touch", "MS-DOS computer"],
    image: img("hp-150-touchscreen-1.jpg"),
  },
  {
    id: "koalapad",
    slug: "koalapad",
    wikiTitle: "KoalaPad",
    year: "1984",
    sortYear: 1984,
    title: "KoalaPad",
    subtitle: "Pressure-sensitive touch tablet for 8-bit home computers.",
    blurb: "Brought absolute-position drawing and menu selection to consumer software years before mainstream mice.",
    tags: ["Graphics Tablet", "Touch Tablet", "Absolute Positioning"],
    image: img("koalapad-1.jpg"),
  },
  {
    id: "microwriter",
    slug: "microwriter",
    wikiTitle: "Microwriter",
    year: "1980",
    sortYear: 1980,
    title: "Microwriter",
    subtitle: "Five-key chorded portable word processor.",
    blurb: "Early wearable-style one-handed text entry device aimed at mobile professionals.",
    tags: ["chording keyboard", "portable computing", "mobile text entry"],
    image: img("microwriter-1.png"),
  },
  {
    id: "nintendo-d-pad-controller",
    slug: "nintendo-d-pad-controller",
    wikiTitle: "Nintendo D-pad controller",
    year: "1985",
    sortYear: 1985,
    title: "Nintendo D-pad controller",
    subtitle: "Cross-shaped directional pad replacing joysticks on consoles.",
    blurb: "Established the dominant discrete directional input paradigm still used in handheld and console gaming.",
    tags: ["D-pad", "Game controller", "NES"],
    image: img("nintendo-d-pad-controller-1.jpg"),
  },
  {
    id: "polhemus-isotrak",
    slug: "polhemus-isotrak",
    wikiTitle: "Polhemus 3Space Isotrak",
    year: "1987",
    sortYear: 1987,
    title: "Polhemus 3Space Isotrak",
    subtitle: "Magnetic 6DOF tracking sensor for 3D interaction.",
    blurb: "First widely available electromagnetic tracker enabling freehand spatial input in VR and CAD.",
    tags: ["6DOF Tracking", "Electromagnetic Tracking", "Virtual Reality"],
    image: img("polhemus-isotrak-1.png"),
  },
  {
    id: "poqet-pc",
    slug: "poqet-pc",
    wikiTitle: "Poqet PC",
    year: "1989",
    sortYear: 1989,
    title: "Poqet PC",
    subtitle: "Credit-card-sized MS-DOS computer with PCMCIA.",
    blurb: "Pushed the limits of portable full-PC interaction years before Palm and Windows CE.",
    tags: ["Palmtop PC", "Power Management", "MS-DOS"],
    image: img("poqet-pc-1.jpg"),
  },
  {
    id: "psion-organiser-ii",
    slug: "psion-organiser-ii",
    wikiTitle: "Psion Organiser II",
    year: "1986",
    sortYear: 1986,
    title: "Psion Organiser II",
    subtitle: "Pocket computer with full QWERTY and expansion slots.",
    blurb: "Early PDA that demonstrated mobile database and calculator interaction models.",
    tags: ["Personal Digital Assistant", "Mobile Database", "Calculator"],
    image: img("psion-organiser-ii-3.jpg"),
  },
  {
    id: "summagraphics-bit-pad",
    slug: "summagraphics-bit-pad",
    wikiTitle: "Summagraphics Bit Pad",
    year: "1977",
    sortYear: 1977,
    title: "Summagraphics Bit Pad",
    subtitle: "Large electromagnetic digitizing tablet for CAD.",
    blurb: "Standardized absolute coordinate input for professional graphics long before consumer tablets.",
    tags: ["Digitizing Tablet", "Absolute Positioning", "Professional Graphics"],
    image: img("summagraphics-bit-pad-1.jpg"),
  },
  {
    id: "writehander",
    slug: "writehander",
    wikiTitle: "WriteHander",
    year: "1978",
    sortYear: 1978,
    title: "WriteHander",
    subtitle: "Twelve-key one-handed chording keyboard for left or right hand.",
    blurb: "Early commercial attempt at compact, eyes-free chorded text entry that predates later wearable keyboards.",
    tags: ["Chorded Keyboard", "Wearable", "Eyes-Free"],
    image: img("writehander-1.jpg"),
  },
  {
    id: "fairlight-cmi",
    slug: "fairlight-cmi",
    wikiTitle: "Fairlight CMI (Computer Musical Instrument)",
    year: "1979",
    sortYear: 1979,
    title: "Fairlight CMI (Computer Musical Instrument)",
    subtitle: "The first digital sampling synthesizer — draw sound with a light pen.",
    blurb: "The first commercially successful creative tool that used a light pen for direct-manipulation content creation. Musicians drew sound waveforms on a CRT and composed visually via Page R, the first graphical pattern sequencer. Years before the Macintosh, it proved that visual, gestural interfaces could power professional creative work.",
    tags: ["Music HCI", "Light Pen", "Digital Audio"],
    image: img("fairlight-cmi-1.jpg"),
  },
  {
    id: "konami-laserscope",
    slug: "konami-laserscope",
    wikiTitle: "Konami LaserScope",
    year: "1990",
    sortYear: 1990,
    title: "Konami LaserScope",
    subtitle: "A voice-activated head-mounted targeting device for the NES — shout 'Fire!' to shoot.",
    blurb: "An astonishingly ambitious consumer wearable from 1990: head-mounted crosshair eyepiece + voice trigger + light gun sensor, all for $39.95. It combined head-based spatial aiming, voice input, heads-up display, and stereo headphones into a single NES peripheral. That it failed spectacularly — the mic triggered on any loud noise, neck fatigue from head-aiming, and you still needed a regular Zapper to make it work — makes it a perfect HCI design-failure case study.",
    tags: ["Voice Control", "Head-Mounted Display", "Gaming"],
    image: img("konami-laserscope-1.jpg"),
  },
  {
    id: "nes-power-pad",
    slug: "nes-power-pad",
    wikiTitle: "NES Power Pad (Family Trainer / Family Fun Fitness)",
    year: "1988",
    sortYear: 1988,
    title: "NES Power Pad (Family Trainer / Family Fun Fitness)",
    subtitle: "The first mass-market full-body exertion interface for home video games — run, jump, stomp.",
    blurb: "A foldable plastic floor mat with 12 pressure sensors that turned the player's entire body into a game controller. Years before DDR, Wii Fit, or Kinect, the Power Pad proved that feet and whole-body movement could be a viable consumer input modality. It pioneered exergaming, invented the 'body as controller' paradigm, and is the direct ancestor of every motion-based game interface that followed. Plus, kids discovered you could cheat by kneeling and slapping the mat with your hands.",
    tags: ["Full-Body Input", "Exergaming", "Floor Mat"],
    image: img("nes-power-pad-1.png"),
  },
  {
    id: "amiga-joyboard",
    slug: "amiga-joyboard",
    wikiTitle: "Amiga Joyboard",
    year: "1983",
    sortYear: 1983,
    title: "Amiga Joyboard",
    subtitle: "The world's first home-console balance board — a foot-operated Atari 2600 controller that gave us the 'Guru Meditation' error screen.",
    blurb: "Arguably the first commercial full-body input device for a home video game console, predating the Wii Balance Board by 23 years. A plastic board you stood on and leaned to control on-screen action, translating gross motor movement into digital directional input through simple mechanical latches.",
    tags: ["Balance Board", "Full-Body Interaction", "Game Controller"],
    image: img("amiga-joyboard-1.jpg"),
  },
  {
    id: "grope-iii",
    slug: "grope-iii",
    wikiTitle: "GROPE-III",
    year: "1990",
    sortYear: 1990,
    title: "GROPE-III",
    subtitle: "The first force-feedback molecular docking system that let chemists physically feel electrostatic forces between drug molecules and protein receptors.",
    blurb: "Repurposed a nuclear-industry teleoperator arm from Argonne National Lab as a 6-DOF haptic force display. Chemists grasped a handle and felt real-time electrostatic forces — steric repulsion, van der Waals attraction, and Coulomb forces — guiding drug molecules into protein receptor sites. Demonstrated a two-fold performance improvement over purely visual interaction and founded the field of haptic rendering.",
    tags: ["Haptics", "Force Feedback", "Scientific Visualization"],
    image: img("grope-iii-1.png"),
  },
  {
    id: "nintendo-hands-free",
    slug: "nintendo-hands-free",
    wikiTitle: "Nintendo Hands Free Controller",
    year: "1989",
    sortYear: 1989,
    title: "Nintendo Hands Free Controller",
    subtitle: "The first accessibility controller produced by a major gaming corporation, operated by chin and breath — 29 years ahead of its time.",
    blurb: "Designed for quadriplegic players and co-developed with Seattle Children's Hospital. A chest-strapped device with a chin-operated joystick for directional movement and a sip-and-puff tube: sipping activates A, puffing activates B. Sold at cost via mail-order with zero marketing, predating Microsoft's Xbox Adaptive Controller by 29 years. Very few units survive today.",
    tags: ["Accessibility", "Sip-and-Puff", "Assistive Technology"],
    image: img("nintendo-hands-free-1.jpg"),
  },
  {
    id: "dlr-spacemouse",
    slug: "dlr-spacemouse",
    wikiTitle: "DLR Control Ball (SpaceMouse)",
    year: "1981",
    sortYear: 1981,
    title: "DLR Control Ball",
    subtitle: "The first 6-DOF force-sensing ball: push, twist, and pull your way through 3D space — built for robots, launched in orbit, and still on desks today",
    blurb: "A tennis-ball-sized sphere that reads minute hand pressures — not position, not movement, but force — and translates them into simultaneous control of all six degrees of freedom. Developed at the German Aerospace Center in 1981. Used on Space Shuttle Columbia. Still in production as the 3Dconnexion SpaceMouse.",
    tags: ["6-DOF Input", "Force Input", "Spatial Controller"],
    image: img("dlr-spacemouse-2.jpg"),
  },
  {
    id: "dragondictate",
    slug: "dragondictate",
    wikiTitle: "DragonDictate",
    year: "1989",
    sortYear: 1989,
    title: "DragonDictate",
    subtitle: "The first large-vocabulary speech-to-text dictation: 30,000 words, one $9,000 DSP board, and an 'Oops' command",
    blurb: "Dragon Systems' husband-wife team put 30,000-word speech recognition on a 386 PC with a $9,000 ISA DSP board and Shure headset. Defined the dictation interaction model: speak, pause, 'Oops' to correct. Life-changing for quadriplegic users.",
    tags: ["Speech Recognition", "Dictation", "Natural Language"],
    image: img("dragondictate-1.png"),
  },
  {
    id: "eyetyper",
    slug: "eyetyper",
    wikiTitle: "EyeTyper",
    year: "1983",
    sortYear: 1983,
    title: "EyeTyper",
    subtitle: "The first camera-based eye-typing device: look to type, dwell to select",
    blurb: "A video camera pointed at one eyeball. A display board with oversized characters. Hold your gaze — and type at 10 words per minute. CMU spinoff Sentient Systems launched EyeTyper in 1983; the company became DynaVox, then Tobii Dynavox.",
    tags: ["Eye-Tracking", "Accessibility", "Camera-Based Input"],
    image: img("eyetyper-1.png"),
  },
  {
    id: "biomuse",
    slug: "biomuse",
    wikiTitle: "BioMuse",
    year: "1990",
    sortYear: 1990,
    title: "BioMuse",
    subtitle: "The first commercial biosignal controller: muscle tension, eye movement, and brainwaves become music",
    blurb: "Eight channels of EMG, EOG, and EEG electrodes feed a $20,000 DSP box. Tensing a forearm muscle triggers a synth note. Shifting your gaze bends a parameter. Built at Stanford's CCRMA by Hugh Lusted and Benjamin Knapp in 1990. Performed in concert halls by Atau Tanaka. Used by NASA, the U.S. Air Force, and a disabled child playing video games at Loma Linda Medical Center.",
    tags: ["Biosignals", "Music", "Accessibility", "Wearable", "EMG"],
    image: img("biomuse/biomuse-system.jpg"),
  },
  {
    id: "etak-navigator",
    slug: "etak-navigator",
    wikiTitle: "Etak Navigator",
    year: "1985",
    sortYear: 1985,
    title: "Etak Navigator",
    subtitle: "The first practical in-car navigation computer, using dead reckoning and a rotating map — years before GPS",
    blurb: "A shoebox-sized 8088 computer in the trunk, a compass on the rear windshield, wheel sensors on the brakes, and maps on high-speed cassette tapes. No GPS — just dead reckoning and a map-matching algorithm that snapped your position to the nearest road. Nolan Bushnell seed-funded it after a 4am yacht conversation. Its heading-up rotating map display and triangular arrow symbol became the universal standard for every navigation app since.",
    tags: ["Navigation", "Automotive", "Map Display", "Location"],
    image: img("etak-navigator/etak-popsci.jpg"),
  },
  {
    id: "nintendo-rob",
    slug: "nintendo-rob",
    wikiTitle: "Nintendo R.O.B. (Robotic Operating Buddy)",
    year: "1985",
    sortYear: 1985,
    title: "Nintendo R.O.B.",
    subtitle: "A physical robot companion that played NES games with you, commanded by light flashes from the TV screen",
    blurb: "R.O.B. is an output device disguised as a friend. The NES draws flashing green and black rectangles on a CRT screen. A phototransistor in R.O.B.'s head decodes the pulses into motor commands. Three DC motors grind into action, and the robot reaches into the real world to press buttons on a second controller. Designed by Gunpei Yokoi. Discontinued by 1988. But before that, it saved Nintendo — retailers wouldn't stock a 'video game console' after the 1983 crash, so they bundled a robot and called it a toy.",
    tags: ["Robotics", "Game Peripheral", "Physical Computing", "Embodied Interaction"],
    image: img("nintendo-rob/rob-studio.jpg"),
  },
  {
    id: "fakespeare-boom",
    slug: "fakespeare-boom",
    wikiTitle: "Fakespeare BOOM (Binocular Omni-Orientation Monitor)",
    year: "1989",
    sortYear: 1989,
    title: "Fakespeare BOOM",
    subtitle: "Press your face against a CRT on a counterbalanced mechanical arm — immersive VR with zero latency, zero weight on your head",
    blurb: "Suspended two 1280x1024 CRTs and LEEP optics inside a viewing hood on a spring-balanced articulated arm. Gripped the handles, pressed your face in, and physically wrestled the display through space — joint encoders giving sub-millisecond 6-DOF tracking. Invented by Mark Bolas (who later mentored Oculus founder Palmer Luckey). Used by NASA, Boeing, and Sandia Labs.",
    tags: ["VR", "Immersive Display", "Head-Coupled Display"],
    image: img("fakespeare-boom-1.gif"),
  },
  {
    id: "buchla-lightning",
    slug: "buchla-lightning",
    wikiTitle: "Buchla Lightning",
    year: "1991",
    sortYear: 1991,
    title: "Buchla Lightning",
    subtitle: "Conjure music from thin air — two infrared wands, one optical tracker, and a DSP that reads your gestures as MIDI",
    blurb: "Don Buchla built an optical gesture-sensing MIDI controller 15 years before the Wii. Two wireless wands emit IR light; a photosensor array triangulates their position, velocity, and acceleration in real time. A TMS370 DSP classifies strikes, sweeps, and zones into MIDI notes and controllers. $1,995, hand-built in Berkeley. Used at IRCAM, CCRMA, and Times Square's millennium celebration.",
    tags: ["Music HCI", "Gesture", "Optical Tracking"],
    image: img("buchla-lightning-1.jpg"),
  },
  {
    id: "seiko-rc1000",
    slug: "seiko-rc1000",
    wikiTitle: "Seiko RC-1000 Wrist Terminal",
    year: "1984",
    sortYear: 1984,
    title: "Seiko RC-1000 Wrist Terminal",
    subtitle: "A wristwatch that plugs into your desktop computer — the first wrist-worn computer terminal, a decade ahead of its time",
    blurb: "The same year the Macintosh shipped, Seiko sold a wristwatch with 2KB RAM, a 12x2 dot-matrix LCD, and an RS-232C serial port. You authored data on a desktop PC, then blasted it to the watch in a 2051-byte dump. Read-only on the wrist. Spawned the WristMac, which flew on Space Shuttle Atlantis in 1991 for the first email from space.",
    tags: ["Wearable", "Wrist-Worn", "Mobile Computing"],
    image: img("seiko-rc1000-1.jpg"),
  },
];

export const exhibits: Exhibit[] = exhibitData.toSorted((a, b) => b.sortYear - a.sortYear || a.title.localeCompare(b.title));

export const featured = exhibits.find((e) => e.feature) ?? exhibits[0]!;
