export type Exhibit = {
  id: string;
  slug: string;
  wikiTitle: string;
  year: string;
  sortYear: number;
  title: string;
  subtitle: string;
  blurb: string;
  tags: string[];
  image: string;
  feature?: boolean;
  span?: 2;
};

const img = (file: string) => `assets/wiki/${file}`;

const exhibitData: Exhibit[] = [
  {
    id: "hubot",
    slug: "hubot",
    wikiTitle: "Hubot",
    year: "c.1983",
    sortYear: 1983,
    title: "Hubot",
    subtitle: "The butler robot with an Atari inside",
    blurb:
      "A 50kg wheeled companion with a CP/M computer, a voice synthesizer, an Atari 2600, and a Polaroid sonar head. Priced at $3,495, it scanned rooms, spoke 1,200 words, and played Defender.",
    tags: ["Robot", "Voice", "Home Computer"],
    image: img("hubot-hardware.webp"),
    feature: true,
  },
  {
    id: "power-glove",
    slug: "nintendo-power-glove",
    wikiTitle: "Nintendo Power Glove",
    year: "1989",
    sortYear: 1989,
    title: "Power Glove",
    subtitle: "A $10,000 NASA glove, shrunk to $90",
    blurb:
      "Mattel had nine months to turn VPL's research-grade DataGlove into a toy. It sold 1.3 million units. \"I love the Power Glove. It's so bad.\"",
    tags: ["Gesture", "Gaming", "Wearable"],
    image: img("power-glove-1.jpg"),
    span: 2,
  },
  {
    id: "atari-mindlink",
    slug: "atari-mindlink",
    wikiTitle: "Atari Mindlink",
    year: "1984",
    sortYear: 1984,
    title: "Atari Mindlink",
    subtitle: "Mind control (actually eyebrow control)",
    blurb:
      "A headband that read forehead muscle tension and called it telepathy. Demoed at CES, then canceled. Testers got headaches from wiggling their brows.",
    tags: ["BCI", "Biofeedback", "Vaporware"],
    image: img("atari-mindlink-2.jpg"),
  },
  {
    id: "videoplace",
    slug: "videoplace",
    wikiTitle: "VIDEOPLACE / Artificial Reality",
    year: "1970s–80s",
    sortYear: 1978,
    title: "VIDEOPLACE",
    subtitle: "Artificial reality without goggles",
    blurb:
      "Myron Krueger put people in shared silhouette worlds using only cameras and projectors. No headsets, no gloves — just your body, glowing on screen.",
    tags: ["Gesture", "Computer Vision", "Art"],
    image: img("videoplace-mediaartnet.jpg"),
  },
  {
    id: "p300-speller",
    slug: "p300-speller",
    wikiTitle: "The P300 Speller",
    year: "1988",
    sortYear: 1988,
    title: "P300 Speller",
    subtitle: "Talking off the top of your head",
    blurb:
      "The first BCI that let you type with brainwaves alone. Focus on a letter in a 6×6 grid; the system reads the P300 spike when your target flashes. 95% accuracy at 12 bits/min.",
    tags: ["Brain Control", "BCI", "EEG"],
    image: img("p300-rowcolumn.webp"),
  },
  {
    id: "vpl",
    slug: "vpl-research",
    wikiTitle: "VPL Research EyePhone & DataGlove",
    year: "1980s",
    sortYear: 1985,
    title: "VPL EyePhone & DataGlove",
    subtitle: "The birth of commercial VR",
    blurb:
      "Jaron Lanier's fiber-optic glove and Fresnel-lens headset defined the visual language of virtual reality. A full system cost $250,000 and ran at 5 fps.",
    tags: ["VR", "Gesture", "Wearables"],
    image: img("vpl-eyephone-demo.jpg"),
    span: 2,
  },
  {
    id: "virtuality",
    slug: "virtuality",
    wikiTitle: "Virtuality Arcade VR System",
    year: "1990",
    sortYear: 1990,
    title: "Virtuality",
    subtitle: "Networked VR in an arcade pod",
    blurb:
      "Amiga 3000s, camcorder LCDs, and magnetic tracking. Dactyl Nightmare let four players fight in cyberspace years before Doom.",
    tags: ["VR", "Arcade", "Multiplayer"],
    image: img("virtuality-1000cs-1.jpg"),
  },
  {
    id: "eyetap",
    slug: "eyetap",
    wikiTitle: "Steve Mann’s EyeTap / Wearable Computing",
    year: "1980s",
    sortYear: 1985,
    title: "EyeTap",
    subtitle: "Wearable computing before it had a name",
    blurb:
      "Steve Mann built camera-display eyeglasses in high school. The computer mediates reality itself — not a HUD, but a reversible eye.",
    tags: ["Wearable", "AR", "Sousveillance"],
    image: img("eyetap-mann-glass-2.jpg"),
  },
  {
    id: "digital-desk",
    slug: "digital-desk",
    wikiTitle: "The Digital Desk",
    year: "1991",
    sortYear: 1991,
    title: "The Digital Desk",
    subtitle: "Paper meets projector",
    blurb:
      "Pierre Wellner pointed a camera and projector at an ordinary desk. Point at printed numbers; the desk calculates and projects the answer onto the paper.",
    tags: ["Tangible", "AR", "Projection"],
    image: img("digital-desk-2.jpg"),
  },
  {
    id: "mandala",
    slug: "mandala",
    wikiTitle: "Mandala / The Vivid Group Gesture VR System",
    year: "1986",
    sortYear: 1986,
    title: "Mandala",
    subtitle: "Full-body VR on an Amiga",
    blurb:
      "The Vivid Group put your live video silhouette inside a virtual world. Punch objects, play drums, dance — 30fps, no controller, on an Amiga 1000.",
    tags: ["Gesture", "VR", "Computer Vision"],
    image: img("mandala-siggraph-1.jpg"),
  },
  {
    id: "put-that-there",
    slug: "put-that-there",
    wikiTitle: "Put-That-There",
    year: "1980",
    sortYear: 1980,
    title: "Put-That-There",
    subtitle: "Voice + gesture at the graphics interface",
    blurb:
      "MIT's Architecture Machine Group let you move shapes by speaking and pointing. It asked clarifying questions when it couldn't understand you.",
    tags: ["Voice", "Gesture", "Multimodal"],
    image: img("put-that-there-video.jpg"),
  },
  {
    id: "speak-spell",
    slug: "speak-spell",
    wikiTitle: "Texas Instruments Speak & Spell",
    year: "1978",
    sortYear: 1978,
    title: "Speak & Spell",
    subtitle: "The first talking chip",
    blurb:
      "Texas Instruments put a 10th-order LPC vocal tract model on a single chip. It taught kids to spell, became an IEEE Milestone, and soundtracked Kraftwerk.",
    tags: ["Voice", "Speech Synthesis", "Toy"],
    image: img("speak-spell-1.jpg"),
  },
  {
    id: "kurzweil",
    slug: "kurzweil-reading-machine",
    wikiTitle: "Kurzweil Reading Machine",
    year: "1976",
    sortYear: 1976,
    title: "Kurzweil Reading Machine",
    subtitle: "Print made audible for the blind",
    blurb:
      "The first omni-font OCR plus a CCD scanner plus a speech synthesizer. Walter Cronkite read his sign-off with it. Stevie Wonder took the first unit home.",
    tags: ["Accessibility", "OCR", "Text-to-Speech"],
    image: img("kurzweil-reading-machine-1.jpg"),
  },
  {
    id: "active-badge",
    slug: "active-badge",
    wikiTitle: "Olivetti Active Badge",
    year: "1992",
    sortYear: 1992,
    title: "Active Badge",
    subtitle: "Your location, broadcast every 10 seconds",
    blurb:
      "Olivetti Research made an IR badge that told the building where you were. Phones followed you. Desktops moved with you. Privacy was born as a question.",
    tags: ["Wearable", "Location-Aware", "Ubicomp"],
    image: img("active-badge-1.gif"),
  },
  {
    id: "twiddler",
    slug: "twiddler",
    wikiTitle: "Handykey Twiddler Chord Keyboard",
    year: "1992",
    sortYear: 1992,
    title: "Twiddler",
    subtitle: "A keyboard in one hand",
    blurb:
      "A chording keypad you hold like a grenade. MIT wearable researchers typed 60 wpm while walking. Still in production 33 years later.",
    tags: ["Input", "Chorded", "One-Handed"],
    image: img("twiddler-original-1.png"),
  },
  {
    id: "gridpad-100",
    slug: "gridpad-100",
    wikiTitle: "GRiDPad 100",
    year: "1989",
    sortYear: 1989,
    title: "GRiDPad 100",
    subtitle: "First commercial tablet computer with pen input.",
    blurb: "Pioneered portable form-factor handwriting recognition and stylus-driven UI on MS-DOS.",
    tags: ["pen computing", "handwriting recognition", "tablet PC"],
    image: img("gridpad-100-1.jpg"),
  },
  {
    id: "heathkit-hero-1",
    slug: "heathkit-hero-1",
    wikiTitle: "Heathkit HERO 1",
    year: "1982",
    sortYear: 1982,
    title: "Heathkit HERO 1",
    subtitle: "Educational robot with sonar, light, and sound sensors.",
    blurb: "Brought programmable physical-world sensing and locomotion to hobbyist HCI experiments.",
    tags: ["Educational Robot", "Programmable Sensing", "Human-Computer Interaction"],
    image: img("heathkit-hero-1-1.jpg"),
  },
  {
    id: "hp-150-touchscreen",
    slug: "hp-150-touchscreen",
    wikiTitle: "HP-150 Touchscreen",
    year: "1983",
    sortYear: 1983,
    title: "HP-150 Touchscreen",
    subtitle: "CRT monitor with infrared touch overlay for office PCs.",
    blurb: "First mass-market computer to ship with direct finger touch as primary input.",
    tags: ["Touchscreen", "Infrared touch", "MS-DOS computer"],
    image: img("hp-150-touchscreen-1.jpg"),
  },
  {
    id: "koalapad",
    slug: "koalapad",
    wikiTitle: "KoalaPad",
    year: "1984",
    sortYear: 1984,
    title: "KoalaPad",
    subtitle: "Pressure-sensitive touch tablet for 8-bit home computers.",
    blurb: "Brought absolute-position drawing and menu selection to consumer software years before mainstream mice.",
    tags: ["Graphics Tablet", "Touch Tablet", "Absolute Positioning"],
    image: img("koalapad-1.jpg"),
  },
  {
    id: "microwriter",
    slug: "microwriter",
    wikiTitle: "Microwriter",
    year: "1980",
    sortYear: 1980,
    title: "Microwriter",
    subtitle: "Five-key chorded portable word processor.",
    blurb: "Early wearable-style one-handed text entry device aimed at mobile professionals.",
    tags: ["chording keyboard", "portable computing", "mobile text entry"],
    image: img("microwriter-1.png"),
  },
  {
    id: "nintendo-d-pad-controller",
    slug: "nintendo-d-pad-controller",
    wikiTitle: "Nintendo D-pad controller",
    year: "1985",
    sortYear: 1985,
    title: "Nintendo D-pad controller",
    subtitle: "Cross-shaped directional pad replacing joysticks on consoles.",
    blurb: "Established the dominant discrete directional input paradigm still used in handheld and console gaming.",
    tags: ["D-pad", "Game controller", "NES"],
    image: img("nintendo-d-pad-controller-1.jpg"),
  },
  {
    id: "polhemus-isotrak",
    slug: "polhemus-isotrak",
    wikiTitle: "Polhemus 3Space Isotrak",
    year: "1987",
    sortYear: 1987,
    title: "Polhemus 3Space Isotrak",
    subtitle: "Magnetic 6DOF tracking sensor for 3D interaction.",
    blurb: "First widely available electromagnetic tracker enabling freehand spatial input in VR and CAD.",
    tags: ["6DOF Tracking", "Electromagnetic Tracking", "Virtual Reality"],
    image: img("polhemus-isotrak-1.png"),
  },
  {
    id: "poqet-pc",
    slug: "poqet-pc",
    wikiTitle: "Poqet PC",
    year: "1989",
    sortYear: 1989,
    title: "Poqet PC",
    subtitle: "Credit-card-sized MS-DOS computer with PCMCIA.",
    blurb: "Pushed the limits of portable full-PC interaction years before Palm and Windows CE.",
    tags: ["Palmtop PC", "Power Management", "MS-DOS"],
    image: img("poqet-pc-1.jpg"),
  },
  {
    id: "psion-organiser-ii",
    slug: "psion-organiser-ii",
    wikiTitle: "Psion Organiser II",
    year: "1986",
    sortYear: 1986,
    title: "Psion Organiser II",
    subtitle: "Pocket computer with full QWERTY and expansion slots.",
    blurb: "Early PDA that demonstrated mobile database and calculator interaction models.",
    tags: ["Personal Digital Assistant", "Mobile Database", "Calculator"],
    image: img("psion-organiser-ii-3.jpg"),
  },
  {
    id: "summagraphics-bit-pad",
    slug: "summagraphics-bit-pad",
    wikiTitle: "Summagraphics Bit Pad",
    year: "1977",
    sortYear: 1977,
    title: "Summagraphics Bit Pad",
    subtitle: "Large electromagnetic digitizing tablet for CAD.",
    blurb: "Standardized absolute coordinate input for professional graphics long before consumer tablets.",
    tags: ["Digitizing Tablet", "Absolute Positioning", "Professional Graphics"],
    image: img("summagraphics-bit-pad-1.jpg"),
  },
  {
    id: "writehander",
    slug: "writehander",
    wikiTitle: "WriteHander",
    year: "1978",
    sortYear: 1978,
    title: "WriteHander",
    subtitle: "Twelve-key one-handed chording keyboard for left or right hand.",
    blurb: "Early commercial attempt at compact, eyes-free chorded text entry that predates later wearable keyboards.",
    tags: ["Chorded Keyboard", "Wearable", "Eyes-Free"],
    image: img("writehander-1.jpg"),
  },
  {
    id: "fairlight-cmi",
    slug: "fairlight-cmi",
    wikiTitle: "Fairlight CMI (Computer Musical Instrument)",
    year: "1979",
    sortYear: 1979,
    title: "Fairlight CMI (Computer Musical Instrument)",
    subtitle: "The first digital sampling synthesizer — draw sound with a light pen.",
    blurb: "The first commercially successful creative tool that used a light pen for direct-manipulation content creation. Musicians drew sound waveforms on a CRT and composed visually via Page R, the first graphical pattern sequencer. Years before the Macintosh, it proved that visual, gestural interfaces could power professional creative work.",
    tags: ["Music HCI", "Light Pen", "Digital Audio"],
    image: img("fairlight-cmi-1.jpg"),
  },
  {
    id: "konami-laserscope",
    slug: "konami-laserscope",
    wikiTitle: "Konami LaserScope",
    year: "1990",
    sortYear: 1990,
    title: "Konami LaserScope",
    subtitle: "A voice-activated head-mounted targeting device for the NES — shout 'Fire!' to shoot.",
    blurb: "An astonishingly ambitious consumer wearable from 1990: head-mounted crosshair eyepiece + voice trigger + light gun sensor, all for $39.95. It combined head-based spatial aiming, voice input, heads-up display, and stereo headphones into a single NES peripheral. That it failed spectacularly — the mic triggered on any loud noise, neck fatigue from head-aiming, and you still needed a regular Zapper to make it work — makes it a perfect HCI design-failure case study.",
    tags: ["Voice Control", "Head-Mounted Display", "Gaming"],
    image: img("konami-laserscope-1.jpg"),
  },
  {
    id: "nes-power-pad",
    slug: "nes-power-pad",
    wikiTitle: "NES Power Pad (Family Trainer / Family Fun Fitness)",
    year: "1988",
    sortYear: 1988,
    title: "NES Power Pad (Family Trainer / Family Fun Fitness)",
    subtitle: "The first mass-market full-body exertion interface for home video games — run, jump, stomp.",
    blurb: "A foldable plastic floor mat with 12 pressure sensors that turned the player's entire body into a game controller. Years before DDR, Wii Fit, or Kinect, the Power Pad proved that feet and whole-body movement could be a viable consumer input modality. It pioneered exergaming, invented the 'body as controller' paradigm, and is the direct ancestor of every motion-based game interface that followed. Plus, kids discovered you could cheat by kneeling and slapping the mat with your hands.",
    tags: ["Full-Body Input", "Exergaming", "Floor Mat"],
    image: img("nes-power-pad-1.png"),
  },
  {
    id: "amiga-joyboard",
    slug: "amiga-joyboard",
    wikiTitle: "Amiga Joyboard",
    year: "1983",
    sortYear: 1983,
    title: "Amiga Joyboard",
    subtitle: "The world's first home-console balance board — a foot-operated Atari 2600 controller that gave us the 'Guru Meditation' error screen.",
    blurb: "Arguably the first commercial full-body input device for a home video game console, predating the Wii Balance Board by 23 years. A plastic board you stood on and leaned to control on-screen action, translating gross motor movement into digital directional input through simple mechanical latches.",
    tags: ["Balance Board", "Full-Body Interaction", "Game Controller"],
    image: img("amiga-joyboard-1.jpg"),
  },
  {
    id: "grope-iii",
    slug: "grope-iii",
    wikiTitle: "GROPE-III",
    year: "1990",
    sortYear: 1990,
    title: "GROPE-III",
    subtitle: "The first force-feedback molecular docking system that let chemists physically feel electrostatic forces between drug molecules and protein receptors.",
    blurb: "Repurposed a nuclear-industry teleoperator arm from Argonne National Lab as a 6-DOF haptic force display. Chemists grasped a handle and felt real-time electrostatic forces — steric repulsion, van der Waals attraction, and Coulomb forces — guiding drug molecules into protein receptor sites. Demonstrated a two-fold performance improvement over purely visual interaction and founded the field of haptic rendering.",
    tags: ["Haptics", "Force Feedback", "Scientific Visualization"],
    image: img("grope-iii-1.png"),
  },
  {
    id: "nintendo-hands-free",
    slug: "nintendo-hands-free",
    wikiTitle: "Nintendo Hands Free Controller",
    year: "1989",
    sortYear: 1989,
    title: "Nintendo Hands Free Controller",
    subtitle: "The first accessibility controller produced by a major gaming corporation, operated by chin and breath — 29 years ahead of its time.",
    blurb: "Designed for quadriplegic players and co-developed with Seattle Children's Hospital. A chest-strapped device with a chin-operated joystick for directional movement and a sip-and-puff tube: sipping activates A, puffing activates B. Sold at cost via mail-order with zero marketing, predating Microsoft's Xbox Adaptive Controller by 29 years. Very few units survive today.",
    tags: ["Accessibility", "Sip-and-Puff", "Assistive Technology"],
    image: img("nintendo-hands-free-1.jpg"),
  },
  {
    id: "dlr-spacemouse",
    slug: "dlr-spacemouse",
    wikiTitle: "DLR Control Ball (SpaceMouse)",
    year: "1981",
    sortYear: 1981,
    title: "DLR Control Ball",
    subtitle: "The first 6-DOF force-sensing ball: push, twist, and pull your way through 3D space — built for robots, launched in orbit, and still on desks today",
    blurb: "A tennis-ball-sized sphere that reads minute hand pressures — not position, not movement, but force — and translates them into simultaneous control of all six degrees of freedom. Developed at the German Aerospace Center in 1981. Used on Space Shuttle Columbia. Still in production as the 3Dconnexion SpaceMouse.",
    tags: ["6-DOF Input", "Force Input", "Spatial Controller"],
    image: img("dlr-spacemouse-2.jpg"),
  },
  {
    id: "dragondictate",
    slug: "dragondictate",
    wikiTitle: "DragonDictate",
    year: "1989",
    sortYear: 1989,
    title: "DragonDictate",
    subtitle: "The first large-vocabulary speech-to-text dictation: 30,000 words, one $9,000 DSP board, and an 'Oops' command",
    blurb: "Dragon Systems' husband-wife team put 30,000-word speech recognition on a 386 PC with a $9,000 ISA DSP board and Shure headset. Defined the dictation interaction model: speak, pause, 'Oops' to correct. Life-changing for quadriplegic users.",
    tags: ["Speech Recognition", "Dictation", "Natural Language"],
    image: img("dragondictate-1.png"),
  },
  {
    id: "eyetyper",
    slug: "eyetyper",
    wikiTitle: "EyeTyper",
    year: "1983",
    sortYear: 1983,
    title: "EyeTyper",
    subtitle: "The first camera-based eye-typing device: look to type, dwell to select",
    blurb: "A video camera pointed at one eyeball. A display board with oversized characters. Hold your gaze — and type at 10 words per minute. CMU spinoff Sentient Systems launched EyeTyper in 1983; the company became DynaVox, then Tobii Dynavox.",
    tags: ["Eye-Tracking", "Accessibility", "Camera-Based Input"],
    image: img("eyetyper-1.png"),
  },
  {
    id: "biomuse",
    slug: "biomuse",
    wikiTitle: "BioMuse",
    year: "1990",
    sortYear: 1990,
    title: "BioMuse",
    subtitle: "The first commercial biosignal controller: muscle tension, eye movement, and brainwaves become music",
    blurb: "Eight channels of EMG, EOG, and EEG electrodes feed a $20,000 DSP box. Tensing a forearm muscle triggers a synth note. Shifting your gaze bends a parameter. Built at Stanford's CCRMA by Hugh Lusted and Benjamin Knapp in 1990. Performed in concert halls by Atau Tanaka. Used by NASA, the U.S. Air Force, and a disabled child playing video games at Loma Linda Medical Center.",
    tags: ["Biosignals", "Music", "Accessibility", "Wearable", "EMG"],
    image: img("biomuse/biomuse-system.jpg"),
  },
  {
    id: "etak-navigator",
    slug: "etak-navigator",
    wikiTitle: "Etak Navigator",
    year: "1985",
    sortYear: 1985,
    title: "Etak Navigator",
    subtitle: "The first practical in-car navigation computer, using dead reckoning and a rotating map — years before GPS",
    blurb: "A shoebox-sized 8088 computer in the trunk, a compass on the rear windshield, wheel sensors on the brakes, and maps on high-speed cassette tapes. No GPS — just dead reckoning and a map-matching algorithm that snapped your position to the nearest road. Nolan Bushnell seed-funded it after a 4am yacht conversation. Its heading-up rotating map display and triangular arrow symbol became the universal standard for every navigation app since.",
    tags: ["Navigation", "Automotive", "Map Display", "Location"],
    image: img("etak-navigator/etak-popsci.jpg"),
  },
  {
    id: "nintendo-rob",
    slug: "nintendo-rob",
    wikiTitle: "Nintendo R.O.B. (Robotic Operating Buddy)",
    year: "1985",
    sortYear: 1985,
    title: "Nintendo R.O.B.",
    subtitle: "A physical robot companion that played NES games with you, commanded by light flashes from the TV screen",
    blurb: "R.O.B. is an output device disguised as a friend. The NES draws flashing green and black rectangles on a CRT screen. A phototransistor in R.O.B.'s head decodes the pulses into motor commands. Three DC motors grind into action, and the robot reaches into the real world to press buttons on a second controller. Designed by Gunpei Yokoi. Discontinued by 1988. But before that, it saved Nintendo — retailers wouldn't stock a 'video game console' after the 1983 crash, so they bundled a robot and called it a toy.",
    tags: ["Robotics", "Game Peripheral", "Physical Computing", "Embodied Interaction"],
    image: img("nintendo-rob/rob-studio.jpg"),
  },
  {
    id: "private-eye",
    slug: "private-eye",
    wikiTitle: "Private Eye",
    year: "1989",
    sortYear: 1989,
    title: "Private Eye",
    subtitle: "The vibrating-mirror monocular display that launched wearable computing and became the Nintendo Virtual Boy",
    blurb: "A 2.5-ounce monochrome display using 280 LEDs and a vibrating mirror to paint a 720x280 image onto your retina. By covering only one eye, your brain fused the display with reality — accidental AR, years before the term existed. MIT researchers wore them daily. Google Glass traces its lineage here.",
    tags: ["Head-Mounted Display", "Wearable", "Augmented Reality"],
    image: img("private-eye/pe-display-unit.png"),
  },
  {
    id: "radio-drum",
    slug: "radio-drum",
    wikiTitle: "Radio Drum / Radio Baton",
    year: "c.1987",
    sortYear: 1987,
    title: "Radio Drum",
    subtitle: "A 3D capacitive spatial controller that tracks two batons in free space — built as a mouse, reborn as an instrument",
    blurb: "Max Mathews, father of computer music, and Bell Labs engineer Bob Boie built a 3D mouse that failed. Then they realized it was a musical instrument. Two batons hover above a capacitance-sensing antenna plate, tracking X, Y, and Z at 100Hz with 1mm precision. No contact required.",
    tags: ["3D Spatial Input", "Music HCI", "Gestural Controller"],
    image: img("radio-drum/rd-ccrma-device.jpg"),
  },
  {
    id: "uforce",
    slug: "uforce",
    wikiTitle: "Broderbund U-Force",
    year: "1989",
    sortYear: 1989,
    title: "U-Force",
    subtitle: "The NES touchless controller with the unfortunate slogan 'Don't Touch!' — nine infrared beams, zero playability, one magnificent failure",
    blurb: "Broderbund Software had never made hardware. Then it shipped a clamshell pad with nine IR emitter-detector pairs that tracked your hand in 3D space above the NES. Ambient light confused it. Calibration drifted. 'Don't Touch!' became an ironic epitaph. A perfect HCI failure study.",
    tags: ["Touchless Input", "Infrared Sensing", "Gaming"],
    image: img("uforce/uf-wikipedia.jpg"),
  },
  {
    id: "fakespeare-boom",
    slug: "fakespeare-boom",
    wikiTitle: "Fakespeare BOOM (Binocular Omni-Orientation Monitor)",
    year: "1989",
    sortYear: 1989,
    title: "Fakespeare BOOM",
    subtitle: "Press your face against a CRT on a counterbalanced mechanical arm — immersive VR with zero latency, zero weight on your head",
    blurb: "Suspended two 1280x1024 CRTs and LEEP optics inside a viewing hood on a spring-balanced articulated arm. Gripped the handles, pressed your face in, and physically wrestled the display through space — joint encoders giving sub-millisecond 6-DOF tracking. Invented by Mark Bolas (who later mentored Oculus founder Palmer Luckey). Used by NASA, Boeing, and Sandia Labs.",
    tags: ["VR", "Immersive Display", "Head-Coupled Display"],
    image: img("fakespeare-boom-1.gif"),
  },
  {
    id: "buchla-lightning",
    slug: "buchla-lightning",
    wikiTitle: "Buchla Lightning",
    year: "1991",
    sortYear: 1991,
    title: "Buchla Lightning",
    subtitle: "Conjure music from thin air — two infrared wands, one optical tracker, and a DSP that reads your gestures as MIDI",
    blurb: "Don Buchla built an optical gesture-sensing MIDI controller 15 years before the Wii. Two wireless wands emit IR light; a photosensor array triangulates their position, velocity, and acceleration in real time. A TMS370 DSP classifies strikes, sweeps, and zones into MIDI notes and controllers. $1,995, hand-built in Berkeley. Used at IRCAM, CCRMA, and Times Square's millennium celebration.",
    tags: ["Music HCI", "Gesture", "Optical Tracking"],
    image: img("buchla-lightning-1.jpg"),
  },
  {
    id: "seiko-rc1000",
    slug: "seiko-rc1000",
    wikiTitle: "Seiko RC-1000 Wrist Terminal",
    year: "1984",
    sortYear: 1984,
    title: "Seiko RC-1000 Wrist Terminal",
    subtitle: "A wristwatch that plugs into your desktop computer — the first wrist-worn computer terminal, a decade ahead of its time",
    blurb: "The same year the Macintosh shipped, Seiko sold a wristwatch with 2KB RAM, a 12x2 dot-matrix LCD, and an RS-232C serial port. You authored data on a desktop PC, then blasted it to the watch in a 2051-byte dump. Read-only on the wrist. Spawned the WristMac, which flew on Space Shuttle Atlantis in 1991 for the first email from space.",
    tags: ["Wearable", "Wrist-Worn", "Mobile Computing"],
    image: img("seiko-rc1000-1.jpg"),
  },
  {
    id: "barcode-battler",
    slug: "barcode-battler",
    wikiTitle: "Barcode Battler / バーコードバトラー",
    year: "1991",
    sortYear: 1991,
    title: "Barcode Battler",
    subtitle: "A handheld game that turned every supermarket barcode into an RPG character — Japan's brief, glorious fad for scanning cereal boxes into warriors",
    blurb: "In 1991, Epoch Co. released a handheld LCD game with a built-in barcode scanner. Swipe any product barcode through its slot — cereal, soup, toilet paper — and an algorithm hashed the digits into character stats for turn-based RPG combat. No graphics, just 7-segment numbers. In Japan, it was a mania: products sold out because kids thought they had lucky barcodes. In the West, it flopped completely. A genuinely novel physical-to-digital bridge, decades before Skylanders or QR-code games.",
    tags: ["Barcode", "Tangible", "Gaming"],
    image: img("barcode-battler-1.png"),
  },
  {
    id: "kramers-talking-glove",
    slug: "kramers-talking-glove",
    wikiTitle: "Talking Glove / The TalkingGlove",
    year: "1988",
    sortYear: 1988,
    title: "Talking Glove",
    subtitle: "A glove that translated American Sign Language fingerspelling into spoken words in real time",
    blurb: "The first portable ASL-to-speech translation system: 14 strain-gauge flex sensors, a beacon recognition algorithm in 16-dimensional hand-space, and a DECtalk speech synthesizer. Built by James Kramer at Stanford (1988–1991) for deaf users to have everyday conversations without an interpreter. The sensor design proved so robust it became the CyberGlove, dominating VR hand-input for two decades before Immersion Corp acquired it and leveraged the patents against Microsoft and Sony.",
    tags: ["Wearable", "Accessibility", "Gesture Recognition"],
    image: img("kramers-talking-glove-1.png"),
  },
  {
    id: "williams-facial-animation",
    slug: "williams-facial-animation",
    wikiTitle: "Performance-Driven Facial Animation",
    year: "1990",
    sortYear: 1990,
    title: "Performance-Driven Facial Animation",
    subtitle: "The first system to use a live actor's real face as a real-time input device for computer-generated animation",
    blurb: "At SIGGRAPH 1990, Lance Williams of Apple ATG introduced the 'electronic mask': retroreflective dots on an actor's face tracked by computer vision, driving a photorealistic 3D CG character in real time. The actor's smile, frown, or raised eyebrow became a real-time animation input stream — the birth of facial performance capture, decades before Avatar or ARKit. Williams later served as Chief Scientist at Walt Disney Animation Studios and won a Technical Academy Award for this work.",
    tags: ["Facial Tracking", "Computer Vision", "Performance Capture"],
    image: img("williams-facial-animation-1.jpg"),
  },
  {
    id: "convolvotron",
    slug: "convolvotron",
    wikiTitle: "Convolvotron",
    year: "1988",
    sortYear: 1988,
    title: "Convolvotron",
    subtitle: "The first real-time 3D audio spatializer — a $15,000 PC board set from NASA's VIEW lab that let you listen through someone else's ears",
    blurb: "Built under a NASA contract by Scott Foster and Crystal River Engineering, the Convolvotron was the first system capable of real-time binaural spatialization of multiple independent sound sources. A custom parallel ALU engine with 128 16×16 multiply-accumulators performed head-related transfer function (HRTF) convolution in real time — as you turned your head, virtual sound sources stayed anchored in 3D space through standard stereo headphones. At $14,995 for a two-board PC set, it spawned a product family (Acoustetron, Beachtron, Alphatron) and was used in landmark VR artworks including Brenda Laurel's Placeholder and Char Davies' Osmose. Its technology was distilled into Aureal's A3D consumer 3D audio API before being acquired by Creative Technology.",
    tags: ["Audio", "Spatial Audio", "VR", "NASA"],
    image: img("convolvotron-1.jpg"),
  },
  {
    id: "headmaster",
    slug: "headmaster",
    wikiTitle: "HeadMaster",
    year: "1986",
    sortYear: 1986,
    title: "HeadMaster",
    subtitle: "An ultrasonic headset that turned head movement into cursor movement — 'If you can move your head, you can move your world'",
    blurb: "The first commercially successful head-operated computer cursor controller. A lightweight headset with three 40 kHz ultrasonic receivers tracked rotational head movement (yaw and pitch) through analog phase-comparison circuitry, sampled at 1,000 Hz with sub-millimeter resolution. A sip-and-puff mouth switch provided mouse-button clicks. Built by Personics Corp in 1986 for $795, later sold by Prentke Romich Company through the 2000s, it came with ScreenTyper — an on-screen keyboard with characters arranged by frequency of use, a decade before soft keyboards became common. Its patent was classified under G06F3/012 'Head tracking input arrangements' — the same classification that would define VR input. Units are held by both the Smithsonian and the Computer History Museum.",
    tags: ["Head Tracking", "Accessibility", "Ultrasonic", "Cursor Control"],
    image: img("headmaster-1.png"),
  },
  {
    id: "vpl-datasuit",
    slug: "vpl-datasuit",
    wikiTitle: "VPL DataSuit",
    year: "1989",
    sortYear: 1989,
    title: "VPL DataSuit",
    subtitle: "The first full-body fiber-optic tracking suit — 30+ sensors across arms, legs, and trunk, your entire body as computer input",
    blurb: "The VPL DataSuit extended the DataGlove's fiber-optic bend sensor technology from one hand to the entire body. Worn as a tight Lycra outfit with 30+ sensors measuring joint angles along arms, legs, and trunk, it made the human body a real-time input device for virtual environments. Combined with the EyePhone HMD and DataGlove in VPL's 'Reality Built for Two' (RB2) — the first multi-user VR system — it embodied Jaron Lanier's concept of 'post-symbolic communication': using body movement as a programming language. Ann Lasko-Harvill designed gender-specific tailoring for different body types. The suit appeared in the 1992 film The Lawnmower Man, introducing full-body VR to mass audiences. Though VPL filed for bankruptcy in 1990, the DataSuit established the template for every full-body tracking system that followed.",
    tags: ["VR", "Wearable", "Motion Capture", "Full-Body"],
    image: img("vpl-datasuit-1.jpg"),
  },
  {
    id: "minsky-sandpaper",
    slug: "minsky-sandpaper",
    wikiTitle: "Minsky Sandpaper / Computational Haptics Sandpaper System",
    year: "1990",
    sortYear: 1990,
    title: "Minsky Sandpaper",
    subtitle: "The 2-DOF force-feedback joystick that synthesized virtual textures through programmable lateral forces, birthing computational haptics.",
    blurb: "The origin story of computational haptics — the moment touch became programmable. Margaret Minsky's 2-DOF force-feedback joystick used a lateral-force algorithm to synthesize virtual textures (sandpaper, rubber, velvet) that users could genuinely feel and distinguish. A wooden box with DC motors, optical encoders, and metal linkages — every haptic device since descends from it.",
    tags: ["Haptics", "Force Feedback", "MIT Media Lab"],
    image: img("minsky-sandpaper-1.webp"),
  },
  {
    id: "quantel-paintbox",
    slug: "quantel-paintbox",
    wikiTitle: "Quantel Paintbox",
    year: "1981",
    sortYear: 1981,
    title: "Quantel Paintbox",
    subtitle: "The $250,000 broadcast graphics workstation that put a pressure-sensitive stylus in the hands of TV artists and defined the look of 1980s television.",
    blurb: "The first computer graphics system designed as an artist's tool rather than an engineer's. Its patented pressure-sensitive stylus and tablet, combined with real-time pop-up menus, let traditionally trained illustrators produce broadcast-quality digital graphics with zero computer knowledge. A decade before consumer tablets and Photoshop, it proved natural gestural interaction could power professional creative work.",
    tags: ["Graphics HCI", "Pressure-Sensitive Stylus", "Broadcast Graphics"],
    image: img("quantel-paintbox-1.jpg"),
  },
  {
    id: "tongue-touch-keypad",
    slug: "tongue-touch-keypad",
    wikiTitle: "Tongue Touch Keypad (TTK) / Tongue Activated Communications Controller",
    year: "1991",
    sortYear: 1991,
    title: "Tongue Touch Keypad",
    subtitle: "The intraoral dental retainer with a nine-key membrane keypad that let quadriplegics control computers by touching their tongue to the roof of their mouth.",
    blurb: "A custom-fitted dental retainer embedding a nine-key keypad, digital encoder, and magnetic-flux radio transmitter — worn on the palate and operated entirely by tongue. Received FDA clearance in 1991, served ~70 quadriplegic users, and established the paradigm for every modern intraoral interface from the Georgia Tech Tongue Drive to MIT's MouthIO.",
    tags: ["Accessibility", "Assistive Technology", "Tongue Interface"],
    image: img("tongue-touch-keypad-1.png"),
  },
  {
    id: "aesthedes",
    slug: "aesthedes",
    wikiTitle: "Aesthedes",
    year: "1984",
    sortYear: 1984,
    title: "Aesthedes",
    subtitle: "The 220 kg Dutch design workstation with 636 dedicated membrane keys, six screens, and a philosophy that designers should never need to learn computers.",
    blurb: "A dedicated graphic-design workstation where every function had a physical key spread across the desk surface — 583 membrane switches on the Aesthedes 1, 636 on the Aesthedes 2. Six screens (three colour, three monochrome) gave every view its own monitor. Ten Motorola 68000 CPUs, 220 kg, and a price tag of $150,000. It designed Dutch banknotes, Heineken labels, and Volvo dashboards before the Macintosh killed it.",
    tags: ["CAD", "Workstation", "Keyboard"],
    image: img("aesthedes-1.jpg"),
  },
  {
    id: "rdi-halcyon",
    slug: "rdi-halcyon",
    wikiTitle: "RDI Halcyon",
    year: "1985",
    sortYear: 1985,
    title: "RDI Halcyon",
    subtitle: "The voice-controlled laserdisc game console that trained itself to your voice, cost $2,500, and sold perhaps ten units before vanishing into legend.",
    blurb: "A consumer device in 1985 that bet its entire identity on speech recognition. No joystick, no keyboard — you talked to it through a noise-canceling headset while it navigated branching laserdisc movies with your spoken commands. Funded by Dragon's Lair profits, killed by the 1983 game crash and a price tag that bought 14 NES consoles. One of the rarest game consoles ever made.",
    tags: ["Gaming", "Voice Recognition", "Laserdisc"],
    image: img("rdi-halcyon-1.jpg"),
  },
  {
    id: "talking-signs",
    slug: "talking-signs",
    wikiTitle: "Talking Signs / Remote Infrared Audible Signage (RIAS)",
    year: "1979",
    sortYear: 1979,
    title: "Talking Signs",
    subtitle: "The invisible city: infrared beams broadcasting spoken directions that only you can hear, turning the built environment into an ambient interface for blind navigation.",
    blurb: "A network of infrared transmitters that broadcast spoken labels on modulated light beams. A blind person carrying a pocket receiver could 'read' the city by pointing it around — doorways, bus stops, ATMs would whisper their names with directional clarity. Codified into US federal building standards (ADAAG 703.7) in 2000. In 2016, the concept became a free smartphone app used by thousands daily.",
    tags: ["Accessibility", "Infrared", "Navigation"],
    image: img("talking-signs-1.jpg"),
  },
  {
    id: "canon-cat",
    slug: "canon-cat",
    wikiTitle: "Canon Cat",
    year: "1987",
    sortYear: 1987,
    title: "Canon Cat",
    subtitle: "Jef Raskin's radical text-centric computer that rejected files, applications, and the mouse.",
    blurb: "No files, no applications, no operating system — just a single unified document stream navigated by content via pink LEAP keys. Designed by the man who initiated the Macintosh, it represents the road not taken in personal computing. The interaction model IS the point.",
    tags: ["HCI", "Input", "Interface Paradigm"],
    image: img("canon-cat-1.jpg"),
  },
  {
    id: "puma-rs-computer-shoes",
    slug: "puma-rs-computer-shoes",
    wikiTitle: "Puma RS Computer Shoes",
    year: "1985",
    sortYear: 1985,
    title: "Puma RS Computer Shoes",
    subtitle: "The first body-worn computer activity tracker — a running shoe you plugged into your Apple IIe.",
    blurb: "The PUMA RS-Computer transformed a shoe into an active sensing peripheral, measuring stride timing to compute distance, speed, and calories. After a run, you physically plugged your shoes into a computer's printer port to download data — a ritual that anticipated every fitness wearable by 20 years.",
    tags: ["HCI", "Wearable", "Sensing"],
    image: img("puma-rs-computer-shoes-1.jpg"),
  },
  {
    id: "versabraille",
    slug: "versabraille",
    wikiTitle: "VersaBraille",
    year: "1979",
    sortYear: 1979,
    title: "VersaBraille",
    subtitle: "The first American refreshable Braille display, turning screen text into raised dots under the fingers.",
    blurb: "A 20-cell piezoelectric Braille display that functioned as notetaker, reading machine, and computer terminal — giving blind users direct tactile access to electronic text for the first time. The same transducer technology invented for this device still powers most Braille displays today.",
    tags: ["HCI", "Accessibility", "Tactile"],
    image: img("versabraille-1.jpg"),
  },
  {
    id: "mbx-expansion-system",
    slug: "mbx-expansion-system",
    wikiTitle: "MBX Expansion System",
    year: "1983",
    sortYear: 1983,
    title: "MBX Expansion System",
    subtitle: "Consumer voice-recognition gaming peripheral that trained on your voice, then let you shout commands at the screen.",
    blurb: "In 1983, Milton Bradley shipped a peripheral that wore a headset, learned your voice, understood spoken game commands, and paired them with a 360-degree analog joystick with a twist knob and a 64-key membrane overlay keypad. Voice-recognition gaming in 1983.",
    tags: ["HCI", "Input", "Voice"],
    image: img("mbx-expansion-system-1.jpg"),
  },
  {
    id: "drawing-prism",
    slug: "drawing-prism",
    wikiTitle: "The Drawing Prism",
    year: "1985",
    sortYear: 1985,
    title: "The Drawing Prism",
    subtitle: "An optical bridge between real brushes and digital pixels — paint directly into a computer with your hands.",
    blurb: "A transparent glass prism that let artists paint with real brushes, fingers, or any light-colored object directly into a computer's frame buffer in 1985. A video camera underneath saw only points of optical contact via frustrated total internal reflection.",
    tags: ["HCI", "Input", "Art"],
    image: img("drawing-prism-1.jpg"),
  },
  {
    id: "datahand-keyboard",
    slug: "datahand-keyboard",
    wikiTitle: "DataHand Keyboard",
    year: "1990",
    sortYear: 1990,
    title: "DataHand Keyboard",
    subtitle: "The keyboard where your fingers never move — each digit rests in a padded well and types by twitching in five directions.",
    blurb: "The most extreme keyboard redesign ever brought to market. Each finger rests in a padded well with five magnetic switches (N/S/E/W + center). No wrist movement, sub-millimeter finger twitches. Invented by Dale Retter to solve his own RSI, prototyped by 1989, sold from 1990.",
    tags: ["HCI", "Input", "Ergonomic"],
    image: img("datahand-keyboard-1.jpg"),
  },
  {
    id: "pencept-penpad",
    slug: "pencept-penpad",
    wikiTitle: "Pencept PenPad",
    year: "1982",
    sortYear: 1982,
    title: "Pencept PenPad",
    subtitle: "A keyboardless terminal that read your handwriting—and your gestures—in 1982",
    blurb: "A terminal replacement with no keyboard—just a pen and tablet. Used MIT-developed user-independent handwriting recognition and gesture commands (circle to select, scribble to delete). CHI '85 demo showed real-time pen computing a decade before the Newton.",
    tags: ["Pen Computing", "Handwriting Recognition", "Gesture"],
    image: img("pencept-penpad-1.jpg"),
  },
  {
    id: "relax-stress-reduction",
    slug: "relax-stress-reduction",
    wikiTitle: "Synapse Relax Stress Reduction System",
    year: "1984",
    sortYear: 1984,
    title: "Synapse Relax Stress Reduction System",
    subtitle: "A video-game company built the first FDA-cleared biofeedback peripheral for home computers—and it almost worked",
    blurb: "An EMG headband, control unit, and software that let you fly a balloon by relaxing. Synapse Software (of Blue Max fame) got FDA clearance as a Class II medical device in 1984. Co-created by legendary game designer Bill Williams. Rarity 9 on AtariMania.",
    tags: ["Biofeedback", "Physiological Computing", "Wearable"],
    image: img("relax-stress-reduction-1.png"),
  },
  {
    id: "exciting-boxing",
    slug: "exciting-boxing",
    wikiTitle: "Exciting Boxing Controller",
    year: "1987",
    sortYear: 1987,
    title: "Exciting Boxing Controller",
    subtitle: "An inflatable humanoid punching bag you physically fought to control a Famicom boxing game",
    blurb: "An inflatable, life-sized boxer with 11 internal pressure sensors that plugged into the Nintendo Famicom. You stood on a mat, put on knitted gloves, and physically punched the bag. Konami, 1987. Full-body motion gaming nearly two decades before the Wii.",
    tags: ["Game Controller", "Full-Body Input", "Motion Gaming", "Famicom"],
    image: img("exciting-boxing-1.jpg"),
  },
  {
    id: "ibva",
    slug: "ibva",
    wikiTitle: "Interactive Brainwave Visual Analyzer (IBVA)",
    year: "1991",
    sortYear: 1991,
    title: "Interactive Brainwave Visual Analyzer (IBVA)",
    subtitle: "The first commercial wireless brain-computer interface — think with your forehead, control a Mac with your mind",
    blurb: "A wireless EEG headband that transmitted brainwaves by radio to a Macintosh, converting alpha and beta rhythms into MIDI notes, visuals, and control signals. Shipped April 1991 by Psychic Lab Inc. Used by Mariko Mori at the Venice Biennale, and by HBO to measure TV audience engagement.",
    tags: ["BCI", "EEG", "Wearable", "Brainwave"],
    image: img("ibva-5.jpg"),
  },
  {
    id: "cave",
    slug: "cave",
    wikiTitle: "CAVE Automatic Virtual Environment",
    year: "1992",
    sortYear: 1992,
    title: "CAVE Automatic Virtual Environment",
    subtitle: "The first room-scale VR — no headset, just a room you walked into",
    blurb: "The CAVE turned the room itself into the display: three walls and a floor projecting stereoscopic 3D that surrounded you, rendered from your tracked viewpoint. You walked naturally. Three other people could stand in there with you, making eye contact and pointing at the same virtual objects.",
    tags: ["VR", "Immersive", "Display"],
    image: img("cave-1.jpg"),
  },
  {
    id: "virtual-fixtures",
    slug: "virtual-fixtures",
    wikiTitle: "Virtual Fixtures",
    year: "1992",
    sortYear: 1992,
    title: "Virtual Fixtures",
    subtitle: "The first augmented reality system — a full upper-body exoskeleton that let you see and feel virtual objects registered in the real world",
    blurb: "In 1992, Louis Rosenberg bolted himself into a full upper-body exoskeleton covered in motors, peered through binocular magnifiers salvaged from a parachute test rig, and reached out to touch a virtual surface that pushed back — the first system to merge real and virtual with force feedback.",
    tags: ["Augmented Reality", "Haptic", "Exoskeleton"],
    image: img("virtual-fixtures-1.jpg"),
  },
  {
    id: "vectrex-3d-imager",
    slug: "vectrex-3d-imager",
    wikiTitle: "Vectrex 3D Imager",
    year: "1983",
    sortYear: 1983,
    title: "Vectrex 3D Imager",
    subtitle: "Color 3D from a black-and-white screen — using a motorized spinning filter disk strapped to your face",
    blurb: "The first commercially released stereoscopic 3D gaming peripheral: a headset with a spinning half-black, half-RGB filter disk synced to the Vectrex vector CRT via PWM motor control. Only ~2,000 units escaped before the 1983 crash. Invented by John Ross, who also created the Vectrex itself.",
    tags: ["3D Display", "Gaming", "Electromechanical", "Stereoscopic"],
    image: img("vectrex-3d-imager.jpg"),
  },
  {
    id: "soundbeam",
    slug: "soundbeam",
    wikiTitle: "Soundbeam",
    year: "1984",
    sortYear: 1984,
    title: "Soundbeam",
    subtitle: "The invisible keyboard in space — ultrasonic sonar that turned body movement into music, then accidentally revolutionized disability music therapy",
    blurb: "Touch-free MIDI controller using 50 kHz sonar beams. Conceived by composer Edward Williams, built by the EMS team (legendary VCS3 synth). Dancers were supposed to use it. Instead, children with profound disabilities made music for the first time. Still in production in 2025.",
    tags: ["Sonar", "Music", "MIDI", "Gestural", "Accessibility", "Embodied"],
    image: img("soundbeam-system.jpg"),
  },
  {
    id: "hard-drivin",
    slug: "hard-drivin",
    wikiTitle: "Hard Drivin' / Race Drivin'",
    year: "1989",
    sortYear: 1989,
    title: "Hard Drivin'",
    subtitle: "The arcade machine that strapped a real DC motor to your steering wheel — and hid a Milliken-level vehicle physics model inside",
    blurb: "First commercial arcade game with continuous force-feedback steering (not vibration — actual road-force resistance). Full manual transmission with clutch and H-pattern shifter. Real vehicle dynamics by Doug Milliken, credited as 'test driver' to keep it secret. 3,318 cabinets built. Every modern force-feedback racing wheel descends from this.",
    tags: ["Force Feedback", "Haptics", "Arcade", "Simulation"],
    image: img("hard-drivin-flyer.jpg"),
  },
  {
    id: "cauzin-softstrip",
    slug: "cauzin-softstrip",
    wikiTitle: "Cauzin Softstrip Reader",
    year: "1985",
    sortYear: 1985,
    title: "Cauzin Softstrip Reader",
    subtitle: "Before QR codes, this $200 wand turned magazine pages into computer data—one manual 30-second swipe at a time.",
    blurb: "The Cauzin Softstrip is the most literal 'paper-to-silicon bridge' ever sold as a consumer computer peripheral. You physically dragged this beige wand over a strip of tiny black-and-white squares printed in Byte magazine, and 5,500 bytes of program code materialized on your Apple II. Co-founder Jack Goldman had founded Xerox PARC. It won MacUser's 'Most Innovative Concept of 1986' and died within three years, outrun by floppy disks and modems.",
    tags: ["Input", "Scanning", "Optical Reader"],
    image: img("cauzin-softstrip-1.jpeg"),
  },
  {
    id: "reading-epg",
    slug: "reading-epg",
    wikiTitle: "Reading Electropalatography (EPG) System",
    year: "1978",
    sortYear: 1978,
    title: "Reading Electropalatography System",
    subtitle: "A computer worn inside the mouth—62 gold electrodes on a custom acrylic palate turned invisible tongue movements into a real-time visual targeting game.",
    blurb: "One of the most intimate human-computer interfaces ever built. A custom-molded acrylic plate, clipped to the user's upper teeth like a retainer, carries 62 gold electrodes in an 8-row grid. When the tongue touches the palate during speech, a CRT monitor illuminates dots wherever contact occurs—turning the invisible act of articulation into a visible, teachable skill. Developed at the University of Reading in 1978.",
    tags: ["Biofeedback", "Speech Therapy", "Accessibility"],
    image: img("reading-epg-1.jpg"),
  },
  {
    id: "synthaxe",
    slug: "synthaxe",
    wikiTitle: "SynthAxe",
    year: "1985",
    sortYear: 1985,
    title: "SynthAxe",
    subtitle: "The £10,000 MIDI guitar that freed pitch from pluck — crashed sequencers with six channels of aftertouch, and fewer than 100 were made",
    blurb: "A fretted MIDI guitar controller with two independent sets of strings at an angle: one for pitch (electrical fret scanning, zero latency) and one for triggering (Hall-effect velocity sensing). Funded by Virgin Group, priced like a small car, built from aerospace materials. Allan Holdsworth called it 'the only guitar synthesizer that really works.' Virgin pulled out, the company folded, and the remaining instruments became holy grails.",
    tags: ["Music", "MIDI", "Gesture"],
    image: img("synthaxe-wikimedia.jpg"),
  },
  {
    id: "sega-hang-on",
    slug: "sega-hang-on",
    wikiTitle: "Sega Hang-On",
    year: "1985",
    sortYear: 1985,
    title: "Sega Hang-On",
    subtitle: "The arcade motorcycle you rode with your whole body, launching Sega's body-sensation revolution.",
    blurb: "Before Hang-On, every arcade game was played with fingers. Then Yu Suzuki built a full-size motorcycle cabinet with a spring-loaded axle that translated body lean into steering. Players straddled it, twisted a real throttle, squeezed real brake levers, and leaned through corners. It sold 20,000 units, was the highest-grossing arcade game of 1985 in the US and 1986 in both Japan and the US, and launched Sega's decade of taikan ('body sensation') motion simulators. Suzuki, a motorcyclist himself, built it for '16-year-old males' who wanted to ride but couldn't get a license.",
    tags: ["Arcade", "Motion", "Full-Body", "Gaming"],
    image: img("sega-hang-on-cabinet.jpg"),
  },
  {
    id: "cmu-sensor-frame",
    slug: "cmu-sensor-frame",
    wikiTitle: "CMU Sensor Frame",
    year: "1985",
    sortYear: 1985,
    title: "CMU Sensor Frame",
    subtitle: "The multi-touch system where pinch-to-zoom was born — built from DRAM memory chips, shown to Steve Jobs.",
    blurb: "Before the iPhone, before Jeff Han's TED talk, there was a metal frame around a CRT monitor at Carnegie Mellon that tracked three fingers, detected their approach angle, and recognized gestures — including canonical pinch-to-zoom in 1985. The sensors were off-the-shelf DRAM memory chips repurposed as crude cameras because CCDs were unavailable. Steve Jobs visited the lab in October 1985 and signed an NDA. The technology was patented, a company was founded, NASA funded a 3D variant — and then nothing. It never shipped. But the idea it proved is now in every pocket.",
    tags: ["Multi-Touch", "Gesture", "Input", "Research"],
    image: img("sensor-frame-hardware.jpg"),
  },
  {
    id: "upic",
    slug: "upic",
    wikiTitle: "UPIC (Unité Polyagogique Informatique CEMAMu)",
    year: "1977",
    sortYear: 1977,
    title: "UPIC",
    subtitle: "Iannis Xenakis's drawing tablet that turned hand-drawn lines directly into synthesized sound.",
    blurb: "A music composition tool with no keyboard, no notation, no code — just drawing. Xenakis, the avant-garde composer who had worked for Le Corbusier, built a large electromagnetic drawing tablet where the X-axis was time and the Y-axis was pitch. Draw a waveform shape → that's the timbre. Draw an envelope → that's the dynamics. Draw a line across the grid → that's the melody. Designed to be usable by children. The entire system fit in under a megabyte. Aphex Twin called it 'under 1mb and it shits on everyone.' His first UPIC piece premiered at the Acropolis of Mycenae.",
    tags: ["Music", "Drawing", "Tablet", "Synthesis"],
    image: img("upic-system.jpg"),
  },
  {
    id: "atarilab",
    slug: "atarilab",
    wikiTitle: "AtariLab",
    year: "1983",
    sortYear: 1983,
    title: "AtariLab",
    subtitle: "The home computer became a scientific instrument when a physics professor plugged a thermistor into the joystick port.",
    blurb: "In 1983, physics professor Priscilla Laws realized the Atari's joystick port was secretly a general-purpose ADC. She built a breakout box that turned the Atari 800 into a real-time lab instrument: plug in a temperature probe, dip it in water, and watch a cooling curve draw itself on the family TV. The software was written by a 15-year-old. Atari collapsed before a dozen planned modules could ship, but Laws's concept lived on — the Universal Laboratory Interface she later co-developed sold 40,000 units through Vernier Software and launched the modern probeware industry.",
    tags: ["Education", "Sensors", "Physical Computing"],
    image: img("atarilab-temperature.jpeg"),
  },
  {
    id: "sgi-dial-box",
    slug: "sgi-dial-box",
    wikiTitle: "SGI Dial and Button Box",
    year: "1986",
    sortYear: 1986,
    title: "SGI Dial and Button Box",
    subtitle: "Eight aluminum knobs, thirty-two buttons, and a design philosophy that said your tools should feel like instruments.",
    blurb: "A dedicated 3D input peripheral for Silicon Graphics IRIS workstations: eight continuous-rotation optical encoder dials and thirty-two programmable buttons in a metal chassis. Animators used their left hand on the dials (rotate, zoom, pan) while the right hand worked the mouse — an asymmetric bimanual workflow later studied by Bill Buxton at the University of Toronto. The dial box represents a lost design philosophy: that professional creative tools deserve dedicated, task-specific physical controls. Every modern 3D app's orbit/zoom/pan navigation inherits the SGI dial layout, but the physical knobs are gone.",
    tags: ["3D Interaction", "Professional Workstation", "Bimanual"],
    image: img("sgi-dial-box-front.jpg"),
  },
  {
    id: "sega-r360",
    slug: "sega-r360",
    wikiTitle: "Sega R360",
    year: "1990",
    sortYear: 1990,
    title: "Sega R360",
    subtitle: "The arcade cabinet that barrel-rolled with you inside",
    blurb:
      "A 1,100 kg gyroscopic arcade sphere that rotated freely through 360 degrees on two axes, physically inverting the player to match in-game flight. $90,000 per unit. Emergency stops on every installation. Only ~100 were ever built.",
    tags: ["Motion Platform", "Arcade", "Kinesthetic", "Simulation"],
    image: img("sega-r360-cabinet.jpg"),
  },
  {
    id: "akai-ewi-1000",
    slug: "akai-ewi-1000",
    wikiTitle: "Akai EWI 1000",
    year: "1987",
    sortYear: 1987,
    title: "Akai EWI 1000",
    subtitle: "The saxophone with no moving keys — just the electricity in your fingers",
    blurb:
      "A wind instrument controller from 1987 where every key is a capacitive touch sensor. Zero mechanical travel, zero clicks. Breath pressure, bite pressure, and finger capacitance combined into three continuous MIDI channels. Nyle Steiner invented it in his Utah basement. Akai sold it to jazz musicians who needed more than a keyboard could give.",
    tags: ["Music", "Capacitive Touch", "Breath Control", "MIDI"],
    image: img("akai-ewi-3020.jpg"),
  },
  {
    id: "armatron",
    slug: "armatron",
    wikiTitle: "Armatron",
    year: "1984",
    sortYear: 1984,
    title: "Armatron",
    subtitle: "A $40 plastic robot arm that made every ten-year-old a teleoperator, no computer required",
    blurb:
      "Tomy/Radio Shack's six-degree-of-freedom tabletop robotic arm, operated through purely mechanical dual joysticks with zero digital electronics. The user's hand movements engage rotating gear drums that map directly onto wrist rotation, elbow bend, shoulder elevation, and gripper — a waldo for the price of a board game.",
    tags: ["Robot", "Teleoperation", "Mechanical", "Toy"],
    image: img("armatron-1.jpg"),
  },
  {
    id: "big-trak",
    slug: "big-trak",
    wikiTitle: "Big Trak",
    year: "1979",
    sortYear: 1979,
    title: "Big Trak",
    subtitle: "A programmable toy tank with a membrane keypad and a Texas Instruments brain, executing 16-step programs in the physical world",
    blurb:
      "Milton Bradley's six-wheeled programmable tank (1979). A TI TMS1000 microcontroller, 16 command memory, and no screen — you typed FORWARD 5, RIGHT 15, FIRE on the keypad and the tank carried out your orders on the living room floor. Carnegie Mellon psychologists adopted it to study how humans learn without instructions.",
    tags: ["Robot", "Programming", "Education", "Toy"],
    image: img("big-trak-1.jpg"),
  },
  {
    id: "scanman",
    slug: "scanman",
    wikiTitle: "Logitech ScanMan",
    year: "1987",
    sortYear: 1987,
    title: "Logitech ScanMan",
    subtitle: "The scanner where your hand was the motor — every twitch came out as a pixel",
    blurb:
      "Logitech's 1987 handheld scanner. Four inches wide, 200 dpi, serial port. No motor: the user physically dragged it across the page at a steady speed, with a roller encoder syncing capture and an LED warning if you moved too fast. Scan quality was a direct function of your hand steadiness.",
    tags: ["Input", "Scanner", "Handheld", "Embodied"],
    image: img("scanman-1.jpg"),
  },
  {
    id: "bat-keyboard",
    slug: "bat-keyboard",
    wikiTitle: "BAT Keyboard",
    year: "1990",
    sortYear: 1990,
    title: "BAT Keyboard",
    subtitle: "Seven keys, one hand, and a tilt that says 'I was designed for a fighter jet cockpit.' NASA helped bring it to Earth.",
    blurb: "The BAT keyboard is one-handed chording reduced to its most elegant form: four finger keys, three thumb keys, a 25-degree tilt, backwards-facing keycaps, and Cherry MX switches with springs so light they had to be custom-modified. Conceived by an Israeli Air Force human-factors specialist who needed to cut fighter-jet control sequences from 32 seconds to 12, then developed with NASA Stennis Space Center for accessibility and spaceflight use.",
    tags: ["Input", "Accessibility", "Wearable"],
    image: img("bat-keyboard-1.jpg"),
  },
  {
    id: "ntt-clearboard",
    slug: "ntt-clearboard",
    wikiTitle: "NTT ClearBoard-1",
    year: "1991",
    sortYear: 1991,
    title: "NTT ClearBoard-1",
    subtitle: "A shared glass drawing surface where your collaborator appears as a ghostly face, maintaining eye contact through a half-silvered mirror.",
    blurb: "ClearBoard-1 is one of the most beautiful and strange interaction models ever built. Two people at remote locations each draw on a large glass pane with marker pens. A half-silvered mirror superimposes the remote collaborator's live video face onto the drawing surface, so you see them 'through' the glass while drawing together.",
    tags: ["CSCW", "Video", "Drawing"],
    image: img("ntt-clearboard-1.jpg"),
  },
  {
    id: "xerox-liveboard",
    slug: "xerox-liveboard",
    wikiTitle: "Xerox LiveBoard",
    year: "1990",
    sortYear: 1990,
    title: "Xerox LiveBoard",
    subtitle: "A 67-inch rear-projection wall that turned a meeting room into a shared computer — and put a laser from a copier in the corner to track your pen.",
    blurb: "The LiveBoard was the moment collaborative computing outgrew the desk. A 67-inch rear-projection display with laser-based pen sensing, built from repurposed Xerox copier parts, let multiple people write simultaneously on a shared digital wall. The Colab room that housed it — with motorized desks, no-glare lighting, and four networked workstations — was an entire physical environment designed around a new way of working together.",
    tags: ["Input", "Display", "CSCW"],
    image: img("xerox-liveboard-1.jpg"),
  },
  {
    id: "butler-in-a-box",
    slug: "butler-in-a-box",
    wikiTitle: "Butler in a Box",
    year: "1983",
    sortYear: 1983,
    title: "Butler in a Box",
    subtitle: "The first voice-controlled home automation system, responding 'Yes, boss' 30 years before Alexa — built by a magician and an ex-IBM programmer.",
    blurb: "The Butler in a Box (1983) pioneered the wake-word-plus-command interaction model that now powers every smart speaker. You trained it to recognize a butler name ('Godfrey,' 'Hobson'), it responded 'Yes, boss,' and then controlled your lights, phone, timers, and alarm — all by voice. Created by professional magician Gus Searcy and former IBM programmer Franz Kavan. Priced at $1,495. It could handle 256 functions, 4 users' voice profiles, and if-then conditional logic. A Smithsonian artifact.",
    tags: ["Voice Control", "Home Automation", "Speech Recognition"],
    image: img("butler-in-a-box-1.jpg"),
  },
  {
    id: "gibson-light-pen",
    slug: "gibson-light-pen",
    wikiTitle: "Gibson Light Pen System (LPS II)",
    year: "1981",
    sortYear: 1981,
    title: "Gibson Light Pen System (LPS II)",
    subtitle: "A professional-grade light pen for the Apple II by the teenager who worked at Stanford AI Lab at age 15 — the launchpad for SpinRite and Security Now!",
    blurb: "Steve Gibson's LPS II (1981) was the finest light pen ever made for an 8-bit microcomputer. A photodetector in the pen tip tracked the CRT's electron beam for 1:1 absolute positioning — drawing directly on screen felt, as one reviewer put it, 'utterly analogous to working with a normal pen.' At $250 it bridged the gap between toy tablets and $1,000+ CAD digitizers. Gibson sold the company to Atari, recovered the rights, licensed to Koala, then founded Gibson Research Corporation — making SpinRite and co-hosting Security Now! for decades.",
    tags: ["Light Pen", "Apple II", "Drawing", "Input"],
    image: img("gibson-light-pen-1.jpg"),
  },
  {
    id: "versatron-footmouse",
    slug: "versatron-footmouse",
    wikiTitle: "Versatron Footmouse",
    year: "1985",
    sortYear: 1985,
    title: "Versatron Footmouse",
    subtitle: "The first commercial foot-operated computer cursor controller — built by a missile-guidance company as their only consumer product.",
    blurb: "The Versatron Footmouse (1985) was the first commercially available foot-operated cursor controller. A keyboard-wedge device that plugged between the keyboard and PC, it injected cursor-key scan codes when you slid your foot across its surface — no mouse drivers needed. The company that built it, Versatron Corporation, was primarily a defense contractor making actuators for Stinger missiles and the Excalibur artillery shell. The footmouse was their one consumer product: a sliding-pedal floor unit designed for accessibility, years before the ADA.",
    tags: ["Foot", "Input", "Accessibility", "Cursor Control"],
    image: img("versatron-footmouse-1.jpg"),
  },
  {
    id: "segarc-3d",
    slug: "segarc-3d",
    wikiTitle: "Sega SubRoc-3D",
    year: "1982",
    sortYear: 1982,
    title: "Sega SubRoc-3D",
    subtitle: "The arcade cabinet you pressed your face into — first stereoscopic 3D video game with a mechanical spinning-shutter periscope.",
    blurb: "Sega's SubRoc-3D (1982) was the first commercial stereoscopic 3D video game, featuring a submarine-periscope-shaped viewer with twin spinning disks that alternated left-eye and right-eye images at 30 fps. Players pressed their face against the eyepiece and gripped the controls below — a full upper-body embodied interface designed by Shikanosuke Ochi, the Sega engineer behind the 1966 Periscope and the first arcade trackball. The 3D system was co-developed with Matsushita (Panasonic) from their experimental 3D television technology. The ColecoVision home port stripped the 3D entirely: you cannot port this experience.",
    tags: ["3D Display", "Arcade", "Embodied Interaction", "Periscope"],
    image: img("subroc3d-cabinet-upright.jpg"),
  },
  {
    id: "bandai-terebikko",
    slug: "bandai-terebikko",
    wikiTitle: "Bandai Terebikko (See 'n Say Video Phone)",
    year: "1988",
    sortYear: 1988,
    title: "Bandai Terebikko",
    subtitle: "The VHS telephone that let cartoon characters call you — Bandai's pre-web interactive television.",
    blurb: "The Bandai Terebikko (1988) was an interactive VHS system shaped like a toy telephone. The handset plugged into a VCR's audio jack and decoded inaudible DTMF-like control tones embedded in licensed anime tapes. When a character 'called,' the phone rang — the child answered and pressed colored buttons to respond to quiz questions. Thirty-three tapes were produced featuring Super Mario, Dragon Ball Z, Sailor Moon, and Anpanman. It was pre-web interactive TV: the telephone as game controller, the VHS tape as bidirectional medium, and the parasocial framing of cartoon characters calling you by name.",
    tags: ["Interactive Television", "VHS", "Toy", "Japan", "Consumer Electronics"],
    image: img("terebikko-system.jpg"),
  },
  {
    id: "two-xl",
    slug: "two-xl",
    wikiTitle: "2-XL",
    year: "1978",
    sortYear: 1978,
    title: "2-XL",
    subtitle: "A talking toy robot that used 8-track tape track-switching as an interactive branching mechanism — analog HCI at its most elegant.",
    blurb: "The Mego 2-XL (1978) was a toy robot with blinking red eyes and a slot for 8-track tape cartridges. It had no CPU, no RAM, no software — just an 8-track player and four buttons. But those buttons switched between the four parallel audio tracks on the tape, creating a seamless interactive conversation. Children pressed Yes or No, and the robot answered with a sarcastic synthesized voice. It was named one of the top ten toys of all time by Playthings magazine and predated digital interactive fiction by using the physical format as the interaction substrate.",
    tags: ["Consumer", "Toy", "Audio", "Interactive", "Robot", "Education"],
    image: img("2-XL_Educational_Toy_Robot_Mego_Corporation_1978.jpg"),
  },
  {
    id: "surf-champ",
    slug: "surf-champ",
    wikiTitle: "Surf Champ",
    year: "1985",
    sortYear: 1985,
    title: "Surf Champ",
    subtitle: "The ZX Spectrum game that shipped with a miniature plastic surfboard — shifting your hands forward, back, and sideways translated weight into fluid-dynamic surfing physics.",
    blurb: "Surf Champ (1985) was a surfing simulator for the ZX Spectrum 48K that came packaged with a 19cm miniature surfboard. The board sat on the keyboard; metal bobbles on its underside pressed different keys when you shifted your hand weight. Real fluid-dynamics algorithms modeled wave behavior at Fistral Beach, Cornwall. Endorsed by the International and European Surfing Associations, it held the first-ever esports tournament — the 1985 World Computer Surfing Championship — and then funding collapsed, leaving only 3,000 copies in existence.",
    tags: ["Gaming", "Sports", "Input", "Proprioception", "Keyboard Overlay"],
    image: img("surf-champ-surfboard-1.jpg"),
  },
  {
    id: "iwata-desktop-force-display",
    slug: "iwata-desktop-force-display",
    wikiTitle: "Iwata Desktop Force Display",
    year: "1990",
    sortYear: 1990,
    title: "Iwata Desktop Force Display",
    subtitle: "A compact desktop haptic device that let you grope blind through invisible virtual space — feeling hard walls, squishy surfaces, and swirling fluid vortices with your bare hand.",
    blurb: "Hiroo Iwata's Desktop Force Display (SIGGRAPH 1990) was a compact haptic device small enough to sit on a desk. Three pantograph linkages supported a handle; the mechanism was so back-drivable and low-inertia that users felt nothing when moving through empty space. Deliberately, no visual display was provided — users relied entirely on force cues to find and explore invisible virtual objects. Hard surfaces felt impenetrable, elastic surfaces gave way like foam, and flow fields twisted the handle in vortices. It proved that force feedback alone is a complete sensory channel for spatial understanding.",
    tags: ["Haptics", "Force Feedback", "VR", "Research", "Input"],
    image: img("iwata-desktop-force-display-1.jpg"),
  },
  {
    id: "atari-video-music",
    slug: "atari-video-music",
    wikiTitle: "Atari Video Music / C-240",
    year: "1977",
    sortYear: 1977,
    title: "Atari Video Music / C-240",
    subtitle: "The first commercial music visualizer — five knobs and a walnut box that turned your stereo into abstract television",
    blurb: "Before Winamp, before iTunes Visualizer, there was a wooden box from Atari with five knobs and twelve buttons. The Atari Video Music (1977) connected between a stereo and a TV, translating audio waveforms into live geometric animations through purely analog circuitry. Designed by Pong engineer Robert Brown, it was discontinued after one year — a glorious commercial failure that established an entire genre. When Sears asked what the developers were smoking, a technician held up a lit joint.",
    tags: ["Audio-Visual", "Analog", "Consumer Electronics"],
    image: img("atari-video-music-1.jpg"),
  },
  {
    id: "grimes-data-glove",
    slug: "grimes-data-glove",
    wikiTitle: "Grimes Digital Data Entry Glove",
    year: "1983",
    sortYear: 1983,
    title: "Grimes Digital Data Entry Glove",
    subtitle: "A chorded keyboard you wear — type by touching your fingers together",
    blurb: "A fabric glove from Bell Labs where touching your fingers together types characters. Unlike position-tracking gloves, the Grimes Glove measures which fingers touch — each fingertip is a switch, your thumb is the common terminal, and typing means tapping finger to thumb in coded patterns. Patented in 1983 by Gary J. Grimes, it reimagined the chorded keyboard as something worn rather than held, years before wearable computing was a term.",
    tags: ["Wearable", "Chorded Keyboard", "Input", "Glove"],
    image: img("grimes-data-glove-1.png"),
  },
  {
    id: "coleco-telstar-arcade",
    slug: "coleco-telstar-arcade",
    wikiTitle: "Coleco Telstar Arcade",
    year: "1977",
    sortYear: 1977,
    title: "Coleco Telstar Arcade",
    subtitle: "The triangular 3-in-1 console whose body WAS the controller — rotate to play",
    blurb: "A triangular prism console where each face is a different game controller: a steering wheel, a light gun, and paddle knobs. To switch games, you physically rotate the whole four-pound unit. Each triangular cartridge contains its own CPU. Designed by Ralph Baer's team at Sanders Associates for Coleco, 1977.",
    tags: ["Gaming", "Input", "Hardware"],
    image: img("coleco-telstar-arcade-1.jpg"),
  },
  {
    id: "sf1-pneumatic",
    slug: "sf1-pneumatic",
    wikiTitle: "Street Fighter Pneumatic Controller",
    year: "1987",
    sortYear: 1987,
    title: "Street Fighter Pneumatic Controller",
    subtitle: "The arcade cabinet that hurt you back — punch pads that sensed force through compressed air",
    blurb: "Capcom's 1987 Street Fighter deluxe cabinet replaced buttons with pneumatic pistons under rubber pads labeled PUNCH and KICK. Striking a pad compressed air in a chamber; a pressure sensor measured the spike to determine light, medium, or heavy attacks. Players got bloody knuckles. Capcom recalled it after roughly 1,000 units. The ROM was lost for decades until reverse-engineered in 2019.",
    tags: ["Arcade", "Force Sensing", "Input"],
    image: img("sf1-pneumatic-1.jpg"),
  },
  {
    id: "vectrex-light-pen",
    slug: "vectrex-light-pen",
    wikiTitle: "Vectrex Light Pen",
    year: "1983",
    sortYear: 1983,
    title: "Vectrex Light Pen",
    subtitle: "The light pen that shouldn't have worked — a bullseye-tracking hack on a vector display",
    blurb: "Light pens normally need a raster scan beam to time position — impossible on a vector display. GCE's John Ross inverted the paradigm: software drew an expanding bullseye pattern that actively hunted for the pen's photodetector. Released in 1983 with Art Master, AnimAction, and Melody Master cartridges, turning the Vectrex into a direct-manipulation creative platform.",
    tags: ["Input", "Pointing", "Gaming"],
    image: img("vectrex-light-pen-1.jpg"),
  },
  {
    id: "heavyweight-champ",
    slug: "heavyweight-champ",
    wikiTitle: "Sega Heavyweight Champ",
    year: "1976",
    sortYear: 1976,
    title: "Sega Heavyweight Champ",
    subtitle: "The first fighting game — and arguably the first motion-controlled video game — with spring-loaded mechanical boxing glove controllers on articulated arms",
    blurb: "The first fighting game, released by Sega in 1976 before microprocessors were standard in arcades. Two spring-loaded mechanical boxing glove controllers on articulated arms — players moved them up/down to aim and pushed inward to punch. Ran on discrete TTL logic: no CPU, no ROMs, just hardwired circuits and switch contacts. Considered lost until original schematics were rediscovered in Bologna in 2025.",
    tags: ["Arcade", "Motion Control", "Physical Controller"],
    image: img("heavyweight-champ-1.jpg"),
  },
  {
    id: "suncom-aerobics-joystick",
    slug: "suncom-aerobics-joystick",
    wikiTitle: "Suncom Aerobics Joystick",
    year: "1983",
    sortYear: 1983,
    title: "Suncom Aerobics Joystick",
    subtitle: "An exercise bike adapter for the Atari 2600 that translated pedaling speed into proportional game input — cardiovascular exergaming, 35 years before Peloton",
    blurb: "A $39.95 adapter that converted pedaling speed into variable-rate fire button presses on the Atari 2600. A magnetic reed switch on the exercise bike flywheel drove a pulse-to-frequency circuit — the faster you pedaled, the faster your ship shot. Only one user account survives. Pioneered the \"sustained exertion rate → in-game action rate\" paradigm used by Peloton, Zwift, and every modern smart trainer.",
    tags: ["Exergaming", "Physical Controller", "Atari 2600"],
    image: img("suncom-aerobics-1.jpg"),
  },
  {
    id: "covox-voice-master",
    slug: "covox-voice-master",
    wikiTitle: "Covox Voice Master",
    year: "1984",
    sortYear: 1984,
    title: "Covox Voice Master",
    subtitle: "Trainable voice command recognition for the Commodore 64 — a consumer speech I/O peripheral that let home computers listen, speak, and obey",
    blurb: "A $89.95 speech I/O peripheral for the Commodore 64 that combined voice recording, playback, and trainable speech recognition. Users trained up to 31 word templates, then controlled software by speaking. Bundled Blackjack was one of the first voice-controlled computer games. Added LEARN, SPEAK, TRAIN, and RECOG commands to BASIC, democratizing voice interaction for home programmers.",
    tags: ["Speech Recognition", "Input", "Home Computer"],
    image: img("covox-voice-master-1.png"),
  },
  {
    id: "liferower",
    slug: "liferower",
    wikiTitle: "LifeRower",
    year: "1986",
    sortYear: 1986,
    title: "LifeRower",
    subtitle: "The rowing machine that was also a video game console — full-body exergaming, 20 years before the Wii",
    blurb: "A commercial rowing machine with a built-in color CRT and video games, released by Bally/Life Fitness in 1986. The rowing mechanism itself was the game controller: an optical encoder measured shaft RPM for on-screen boat speed, a microswitch synchronized the on-screen rower's animation to the user's strokes, and a magnetic particle brake provided constant-torque resistance. Two games built in: competitive boat racing and shark chase. Priced at $2,000–3,000, sold to commercial gyms. Predates Peloton and Ring Fit by 35 years.",
    tags: ["Exergaming", "Fitness", "Rowing", "Game Console"],
    image: img("liferower-1.png"),
  },
  {
    id: "sega-ai-computer",
    slug: "sega-ai-computer",
    wikiTitle: "Sega AI Computer",
    year: "1986",
    sortYear: 1986,
    title: "Sega AI Computer",
    subtitle: "A children's computer that understood natural language — touch overlays, speech recognition, and Prolog AI in 1986",
    blurb: "An extremely rare educational computer released by Sega in Japan in 1986, featuring a touch surface with swappable overlay sheets, speech recognition and synthesis, and a Prolog-based AI engine for natural language processing. Children used physical overlays to interact with lessons; the system's diary app asked about their day and generated grammatically correct entries from one-word answers. Built by Yamaha with software by CSK Research Institute. Only a handful survive; the complete ROM set was preserved and emulated in MAME in 2024.",
    tags: ["Touch", "Speech Recognition", "Children's Computing", "AI", "Home Computer"],
    image: img("sega-ai-computer-unit.jpg"),
  },
  {
    id: "ibutton",
    slug: "ibutton",
    wikiTitle: "Dallas Semiconductor iButton",
    year: "1990",
    sortYear: 1990,
    title: "Dallas Semiconductor iButton",
    subtitle: "A 16mm steel can that turned touch into digital identity",
    blurb: "A microchip in a 16mm stainless steel can — shaped like a watch battery — that contained a unique, factory-lasered 64-bit serial number. To identify yourself to a computer, you pressed the button against a reader. Touch = identity. Invented by Dallas Semiconductor in 1990, the iButton used the 1-Wire protocol (data and power over a single conductor) and spawned an ecosystem of memory, clock, temperature, and cryptographic variants. Used as electronic keys, time clock tokens, Istanbul's Akbil transit smart ticket, and eventually the Java Ring (1998) — a finger-worn iButton with a full Java virtual machine.",
    tags: ["Tangible", "Identity", "Token", "Touch", "Ubiquitous Computing"],
    image: img("ibutton-token.jpg"),
  },
  {
    id: "trs80-voice-synthesizer",
    slug: "trs80-voice-synthesizer",
    wikiTitle: "TRS-80 Voice Synthesizer",
    year: "1979",
    sortYear: 1979,
    title: "TRS-80 Voice Synthesizer",
    subtitle: "The speech synthesizer you programmed by writing to the screen",
    blurb: "A speech synthesis peripheral for the TRS-80 Model I that worked through the strangest interface imaginable: it read phoneme codes directly from video memory. To make it speak, you wrote ASCII phoneme strings like '?K6MPY(UT?' to the right half of the bottom screen line — the synthesizer would read them and produce speech. Each of the 60 phonemes was mapped to an arbitrary ASCII character (6=UH1, $=TH, +=NG), turning speech programming into a secret code. Built around the Votrax SC-01-A chip. Sold for $399 in 1979 by Radio Shack; discontinued in 1983. There was no text-to-speech engine — every word had to be manually decomposed into phonemes.",
    tags: ["Speech Synthesis", "TRS-80", "Peripheral", "Accessibility"],
    image: img("trs80-voice-synthesizer.jpg"),
  },
  {
    id: "stompin",
    slug: "stompin",
    wikiTitle: "Stompin'",
    year: "1986",
    sortYear: 1986,
    title: "Stompin'",
    subtitle: "The arcade game you play with your feet — Bushnell's 'floorplay' controller that invented the dance pad",
    blurb: "A 1986 arcade game by Bally Sente that introduced the first foot-operated grid controller in arcade history — a 3×3 matrix of weight-sensitive pads embedded in a floor platform, each surrounded by individually-addressable LED light segments. To play, you stomped on bugs and mice by placing your feet on the corresponding pads while a Motorola 6809 CPU read a 9-bit shift register to determine your foot position and controlled 24 LED segments through a second shift register. Bally Sente coined the term 'floorplay' for this new interaction category. The patent (US 4,720,789) named Nolan K. Bushnell as co-inventor and explicitly described the system as both a video game and exercise apparatus — anticipating exergaming by decades. This is the direct ancestor of Dance Dance Revolution and every foot-operated rhythm game that followed.",
    tags: ["Arcade", "Foot Controller", "Exergaming", "Floor Interface", "Input"],
    image: img("stompin-patent-fig1.png"),
  },
  {
    id: "electroglottograph",
    slug: "electroglottograph",
    wikiTitle: "Kay Visi-Pitch / Electroglottograph",
    year: "1987",
    sortYear: 1987,
    title: "Kay Visi-Pitch / Electroglottograph",
    subtitle: "A computer that reads what your vocal cords are doing, not what they sound like",
    blurb: "The Kay Visi-Pitch Model 6300 (1987) connected an electroglottograph (EGG) to an IBM PC via a custom ISA-bus ADC card. Two neck electrodes passed a 2-3 MHz current across the larynx, measuring vocal fold contact impedance — producing a waveform of laryngeal movement even during silent speech, whispering, or subvocalization. This is not a microphone and not EMG: it measures the internal mechanical dance of your vocal cords through tissue impedance. Used in speech therapy clinics as real-time visual biofeedback, patients could see their own vocal fold contact patterns on screen and learn to adjust them. The technology works when you produce no audible sound at all, making it a proto-'silent speech interface' decades before modern BCI research attempted the same. Kay Elemetrics (founded 1949) shipped the Model 6087 standalone Visi-Pitch in 1977 and added PC connectivity with the Model 6300 in 1987.",
    tags: ["Biosignal Input", "Medical", "Biofeedback", "Speech", "Wearable", "Accessibility"],
    image: img("eg2-pcx-electroglottograph.jpg"),
  },
  {
    id: "action-max",
    slug: "action-max",
    wikiTitle: "Worlds of Wonder Action Max",
    year: "1987",
    sortYear: 1987,
    title: "Worlds of Wonder Action Max",
    subtitle: "A VHS tape is the game cartridge, and a light gun reads screen brightness to score your shots",
    blurb: "The Action Max (1987) is a video game console that has no game cartridge and no on-screen graphics of its own. Game content lives entirely on ordinary VHS tapes; the console only registers trigger pulls from a jet-fighter-shaped 'Sonic Fighter' light gun, increments a 2-digit LED score on its base, and flashes a separate suction-cup 'Score Signal' lamp on the TV bezel. The light gun's photocell detects timed brightness flashes baked into the VHS video at the moments a target is shootable — subtle flicker patterns even encode target type (enemy vs. civilian). Built on a 4-bit Hitachi HD401010 microcontroller, launched the same quarter its parent company (Worlds of Wonder, founded by ex-Atari sales president Don Kingsborough) filed for Chapter 11, and dead within five launch tapes: Sonic Fury, .38 Ambush Alley, Blue Thunder, Hydrosub: 2021, and The Rescue of Pops Ghostly. A uniquely weird HCI paradigm: VHS-as-game-medium, light gun + photocell as input, console as score-only overlay.",
    tags: ["Light Gun", "VHS", "Video Game Console", "Optical Input", "Commercial Failure", "Input"],
    image: img("action-max-set.jpg"),
  },
  {
    id: "lightwriter-sl1",
    slug: "lightwriter-sl1",
    wikiTitle: "Toby Churchill Lightwriter SL1",
    year: "c. 1985",
    sortYear: 1985,
    title: "Toby Churchill Lightwriter SL1",
    subtitle: "A speech prosthesis with two screens — one for the typer, one facing the listener",
    blurb: "The Lightwriter is a portable augmentative and alternative communication (AAC) device invented by Toby Churchill, a British engineer who lost his own speech and almost all motor function to encephalitis contracted in 1968 at age 21. The defining feature of the SL1 (c. 1985) is a pair of back-to-back LCD displays: one faces the user, who composes the message on a QWERTY keyboard with a cursor; the other faces the listener, who reads the same text appearing character-by-character as it is typed. A built-in speech synthesizer then speaks the message aloud. This dual-display shared-workspace paradigm is the Lightwriter's distinctive HCI contribution — a speech prosthesis explicitly designed for face-to-face conversation, so both parties can read what is being typed in real time. Distinct from VersaBraille (Braille terminal), Tongue Touch Keypad (input peripheral), and Kay Visi-Pitch (clinical voice measurement). Toby Churchill Ltd was founded in 1973; descendants remain in production today under Abilia Ltd.",
    tags: ["AAC", "Accessibility", "Speech Synthesis", "Dual Display", "Medical", "Output"],
    image: img("lightwriter-sl35.jpg"),
  },
  {
    id: "optacon-ii",
    slug: "optacon-ii",
    wikiTitle: "Optacon II (Tactile Reading Machine)",
    year: "1985",
    sortYear: 1985,
    title: "Optacon II (Tactile Reading Machine)",
    subtitle: "Feel the shape of a printed letter vibrating against your fingertip, in real time — no OCR, no speech",
    blurb: "The Optacon (OPtical to TActile CONverter) is a direct sensory-substitution reading machine for blind users, conceived at Stanford in 1962 by EE professor John Linvill — motivated by his daughter Candy, blind from age three — and developed with Jim Bliss at SRI. A handheld camera images a single letterspace of printed text, and a 24×6 array of piezoelectric bimorph-driven vibrating pins maps that image 1:1 onto the user's index fingertip. The user reads by feeling the letters as flowing dot patterns at ~250–300 Hz — pure visual-to-tactile substitution with no OCR, no speech, no text storage; the human does the recognition in real time, at 30–100 wpm after extensive training. Roughly 15,000 units were sold across the 1971–1996 production life. The Optacon II (1985), co-developed with Canon Inc., was the redesigned variant with improved packaging and a computer/terminal interfacing capability allowing users to read CRT screens — squarely within the museum's window. A cost-driven decision reduced the tactile array from 144 to 100 pins and hurt usability badly enough that long-time users largely stuck with the older model.",
    tags: ["Accessibility", "Sensory Substitution", "Tactile Output", "Reading Machine", "Piezoelectric", "Output"],
    image: img("optacon-ii.jpg"),
  },
  {
    id: "adventure-vision",
    slug: "adventure-vision",
    wikiTitle: "Entex Adventure Vision",
    year: "1982",
    sortYear: 1982,
    title: "Entex Adventure Vision",
    subtitle: "A 150-pixel-wide red display synthesized by a spinning mirror sweeping a vertical column of 40 LEDs — a mechanical-scan display in a battery-powered handheld",
    blurb: "The Entex Adventure Vision (1982) is a handheld tabletop game console whose display is a 150×40 monochrome red raster, synthesized by a spinning flat mirror sweeping a single vertical column of 40 red GaAsP LEDs. An Intel 8048 microcontroller strobes the LEDs in patterns synchronized to the mirror's angular position; persistence of vision blends the 40-LED column into an apparent 150×40 pixel image at ~15 fps. The player holds the bulky 13.25 × 10 × 9 inch device with two hands: a 4-direction digital joystick in the center, with 4 physical buttons arranged symmetrically (2 left, 2 right) so left- and right-handed players each get a fire button and a secondary button. Only 4 game cartridges shipped (Defender as the pack-in, Super Cobra, Turtles, Space Force). It is an evolutionary dead-end whose only spiritual descendant is Nintendo's 1995 Virtual Boy. Roughly 10,000 systems sold (per collector consensus), at $79.95 MSRP, before Entex folded in 1983. The rotating-mirror mechanical-scan display is fundamentally different from CRT, LCD, and the Vectrex vector approach already in the museum, giving the collection a fourth display paradigm.",
    tags: ["Display", "Mechanical Scan", "Rotating Mirror", "Handheld", "LED", "Commercial Failure", "Output"],
    image: img("adventure-vision-1.jpg"),
  },
  {
    id: "bbc-domesday-project",
    slug: "bbc-domesday-project",
    wikiTitle: "BBC Domesday Project",
    year: "1986",
    sortYear: 1986,
    title: "BBC Domesday Project",
    subtitle: "A million contributors, two laserdiscs, a trackball and 16 function keys — the pre-Web national point-and-click information system that became unreadable within 15 years",
    blurb: "The BBC Domesday Project (1986) was a national interactive multimedia system launched by the BBC to mark the 900th anniversary of the Domesday Book. A BBC Master AIV computer, a Philips VP415 laserdisc player with internal genlock and video-mixing board, a Marconi RB2 trackball, and a printed 16-key function-key overlay strip put a pre-Web point-and-click GUI into schools and libraries — running on a genlocked laserdisc/computer overlay, predating the World Wide Web. Over 1 million people crowd-contributed photographs and text entries; ~9,000 schools participated. The two LV-ROM discs (54,000 image frames and ~300 MB of digital data per side, interleaved with error protection) carried a national map browser of 24,000 4 km × 3 km blocks from Ordnance Survey, a topic hierarchy with natural-language search (the Porter Stemming Algorithm — yes, that Porter), and a Bosch FGS-4000-rendered 'Landscape of Knowledge' virtual art gallery with 9 'surrogate walks' (early non-immersive VR). By 2002 the Observer ran the famous headline 'Digital Domesday Book lasts 15 years not 1000' — the playback system had become unreadable. Recovery took a multi-decade, multi-institution effort (CAMiLEON, BBC R&D, domesday1986.com, Domesday Reloaded 2011, Domesday86 2020+). Fewer than 2,000 systems sold at ~£5,000 each. Distinct from RDI Halcyon (laserdisc game), Bandai Terebikko (VHS quiz), and Action Max (VHS light-gun shooter) — the only general-purpose national reference/information system in the candidate pool, and the canonical digital-obsolescence parable.",
    tags: ["Laserdisc", "Interactive Video", "Trackball", "GUI", "Reference System", "Crowdsourcing", "Digital Obsolescence", "Genlock", "Input"],
    image: img("bbc-domesday-system.jpg"),
  },
  {
    id: "hologram-time-traveler",
    slug: "hologram-time-traveler",
    wikiTitle: "Sega Hologram Time Traveler",
    year: "1991",
    sortYear: 1991,
    title: "Sega Hologram Time Traveler",
    subtitle: "A curved mirror projects live-action actors as free-standing 3D figures above the cabinet — and a coin-bought 'time reversal' button rewinds your mistakes",
    blurb: "Sega Hologram Time Traveler (1991) is a 1991 arcade cabinet that produces the visual impression of free-standing 3D actors by reflecting a 20-inch Sony CRT, mounted face-up inside the cabinet, off a large black hemispherical concave mirror. The reflected light forms a real image — not a virtual one — that appears to hover in mid-air above a small darkened stage ringed by neon geometric blocks. The actors are pre-recorded live-action footage on laserdisc; the player interacts via a 4-way joystick, an action button, and a 'time reversal' button that rewinds the last few seconds of a failed segment so the player can retry without restarting — additional time-reversal 'cubes' are bought with inserted coins between levels. Designed by Rick Dyer, creator of Dragon's Lair (1983), through his Virtual Image Productions studio and GTE ImagiTrek / GTE Interactive Media; Sega published. The optical system is described in US Patent 4,776,118 ('Display device,' Goro Mizuno / Decos Co. Ltd, filed 1986, granted 1988). The 'hologram' is marketing language — the patent explicitly calls it a 'real image' produced by a single direct reflection, a Pepper's-ghost-lineage stage illusion, not laser-interference holography. The cabinet was fragile: Sega Retro (citing System16) confirms Time Traveler cabinets had hardware problems and Sega's 1992 Holosseum was produced specifically as a replacement. Where Hard Drivin' embodies the player through force feedback and Sega R360 through gyroscopic motion, Time Traveler embodies through perceptual illusion — the interface's claim is that the actor stands physically in front of you. The 'time reversal' input is a distinct HCI mechanic not present in any other museum artifact: a coin-purchasable mechanical undo for branching video.",
    tags: ["Display", "Holographic", "Laserdisc", "Arcade", "Branching Video", "Time Reversal", "Commercial Failure", "Output"],
    image: img("hologram-time-traveler-cabinet.jpg"),
  },
  {
    id: "simon",
    slug: "simon",
    wikiTitle: "Milton Bradley Simon",
    year: "1978",
    sortYear: 1978,
    title: "Milton Bradley Simon",
    subtitle: "A Texas Instruments TMS1000 microcontroller, four mechanical lighted push-buttons, and an A-major triad — the closed-loop microcontroller-mediated memory game that defined a genre",
    blurb: "Simon (1978) is the canonical, patent-protected, microcontroller-driven consumer artifact that defined the audio-visual memory-game genre — a closed-loop microcontroller-mediated human-machine interaction in purest form. A Texas Instruments TMS1000 4-bit single-chip microcontroller (one of the earliest consumer applications of a microcontroller, explicitly named in US Patent 4,207,087) generates a stochastic sequence of tone + light events. The player perceives the stimulus and responds by pressing one of four mechanical push-button keyswitches — translucent colored quadrants (red, green, blue, yellow) lit from behind by incandescent bulbs — each playing a distinct tone. The machine evaluates the response and adaptively lengthens or accelerates the next stimulus, with five game variants described in the patent (solo, two-player, timed, record/playback of tunes, multi-player elimination). The tones form an A major triad in second inversion (resembling a bugle fanfare — Baer's inspiration), so any sequence is always harmonic regardless of order. Invented by Ralph H. Baer (already in the museum via Coleco Telstar Arcade, his earlier work at Sanders Associates) and Howard J. Morrison at Marvin Glass and Associates in Chicago, with software by Lenny Cope and much of the assembly code by Charles Kapps (Temple University). Patent US 4,207,087 filed September 1977, granted June 1980. Launched at Studio 54 in New York City in 1978 at $24.95; ~1 million sold in the first year; top-selling toy of the 1978 Christmas season. Still in production by Hasbro today, with dozens of variants across four decades. Simon is Baer's most iconic mass-market artifact and gives the museum a coherent Ralph-Baer thread alongside Coleco Telstar Arcade (1977).",
    tags: ["Microcontroller", "Audio-Visual", "Memory Game", "Consumer", "Closed-Loop", "TMS1000", "Input"],
    image: img("simon-game.jpg"),
  },
  {
    id: "telesar-i",
    slug: "telesar-i",
    wikiTitle: "TELESAR I",
    year: "1981–1984",
    sortYear: 1982,
    title: "TELESAR I",
    subtitle: "First working telexistence system — a head-coupled stereoscopic telepresence rig that produced a genuine out-of-body sensation in every operator who tried it",
    blurb: "TELESAR I (1981–1984) was the world's first working telexistence system, developed by Susumu Tachi at Japan's Mechanical Engineering Laboratory in Tsukuba. The operator wore a stereo head-mounted display carried by a counterbalanced 6-DOF link mechanism that tracked head movements in real time, while a parallel-link master arm captured hand and arm motion. On the remote side, an anthropomorphic slave robot (60 kg, 7-DOF arm, stereo CCD cameras on a 3-DOF neck, binaural microphones, gripper hand) replicated the operator's movements. Four Intel 286/386 computers processed the control loops at 10 ms. When Tachi first tested the visual-only prototype in late 1981, he experienced what he described as an out-of-body sensation (yūtai ridatsu) — he could observe his real self raising and lowering hands from the robot's perspective. This was independently confirmed by visitors Grant Fjermedal (documented in The Tomorrow Makers, 1986) and Howard Rheingold (documented in Virtual Reality, 1991). The system was funded through Japan's eight-year national 'Advanced Robot Technology in Hazardous Environments' project (1983–1990). The core HCI principle — that tight visuomotor coupling between human and machine creates genuine presence — predates and underlies all modern VR and telepresence. The 'telexistence' concept (1980) was Tachi's independent Japanese invention, contemporaneous with but distinct from Marvin Minsky's 'telepresence' (1980) — telexistence explicitly includes virtual environments and frames the avatar robot as a virtual exoskeleton, a dialectical synthesis (Aufhebung) of the dangerous physical exoskeleton and autonomous supervised robot paradigms.",
    tags: ["Telepresence", "Robotics", "VR", "HMD", "Japan", "Out-of-Body", "Master-Slave"],
    image: img("telesar-i-system.png"),
  },
];

export const exhibits: Exhibit[] = exhibitData.toSorted((a, b) => b.sortYear - a.sortYear || a.title.localeCompare(b.title));
export const exhibitsByNewestAdded: Exhibit[] = exhibitData.toReversed();

export const featured = exhibits.find((e) => e.feature) ?? exhibits[0]!;
