export type Exhibit = {
  id: string;
  slug: string;
  wikiTitle: string;
  year: string;
  sortYear: number;
  title: string;
  subtitle: string;
  blurb: string;
  tags: string[];
  image: string;
  feature?: boolean;
  span?: 2;
};

const img = (file: string) => `assets/wiki/${file}`;

const exhibitData: Exhibit[] = [
  {
    id: "hubot",
    slug: "hubot",
    wikiTitle: "Hubot",
    year: "c.1983",
    sortYear: 1983,
    title: "Hubot",
    subtitle: "The butler robot with an Atari inside",
    blurb:
      "A 50kg wheeled companion with a CP/M computer, a voice synthesizer, an Atari 2600, and a Polaroid sonar head. Priced at $3,495, it scanned rooms, spoke 1,200 words, and played Defender.",
    tags: ["Robot", "Voice", "Home Computer"],
    image: img("hubot-hardware.webp"),
    feature: true,
  },
  {
    id: "power-glove",
    slug: "nintendo-power-glove",
    wikiTitle: "Nintendo Power Glove",
    year: "1989",
    sortYear: 1989,
    title: "Power Glove",
    subtitle: "A $10,000 NASA glove, shrunk to $90",
    blurb:
      "Mattel had nine months to turn VPL's research-grade DataGlove into a toy. It sold 1.3 million units. \"I love the Power Glove. It's so bad.\"",
    tags: ["Gesture", "Gaming", "Wearable"],
    image: img("power-glove-1.jpg"),
    span: 2,
  },
  {
    id: "atari-mindlink",
    slug: "atari-mindlink",
    wikiTitle: "Atari Mindlink",
    year: "1984",
    sortYear: 1984,
    title: "Atari Mindlink",
    subtitle: "Mind control (actually eyebrow control)",
    blurb:
      "A headband that read forehead muscle tension and called it telepathy. Demoed at CES, then canceled. Testers got headaches from wiggling their brows.",
    tags: ["BCI", "Biofeedback", "Vaporware"],
    image: img("atari-mindlink-2.jpg"),
  },
  {
    id: "videoplace",
    slug: "videoplace",
    wikiTitle: "VIDEOPLACE / Artificial Reality",
    year: "1970s–80s",
    sortYear: 1978,
    title: "VIDEOPLACE",
    subtitle: "Artificial reality without goggles",
    blurb:
      "Myron Krueger put people in shared silhouette worlds using only cameras and projectors. No headsets, no gloves — just your body, glowing on screen.",
    tags: ["Gesture", "Computer Vision", "Art"],
    image: img("videoplace-mediaartnet.jpg"),
  },
  {
    id: "p300-speller",
    slug: "p300-speller",
    wikiTitle: "The P300 Speller",
    year: "1988",
    sortYear: 1988,
    title: "P300 Speller",
    subtitle: "Talking off the top of your head",
    blurb:
      "The first BCI that let you type with brainwaves alone. Focus on a letter in a 6×6 grid; the system reads the P300 spike when your target flashes. 95% accuracy at 12 bits/min.",
    tags: ["Brain Control", "BCI", "EEG"],
    image: img("p300-rowcolumn.webp"),
  },
  {
    id: "vpl",
    slug: "vpl-research",
    wikiTitle: "VPL Research EyePhone & DataGlove",
    year: "1980s",
    sortYear: 1985,
    title: "VPL EyePhone & DataGlove",
    subtitle: "The birth of commercial VR",
    blurb:
      "Jaron Lanier's fiber-optic glove and Fresnel-lens headset defined the visual language of virtual reality. A full system cost $250,000 and ran at 5 fps.",
    tags: ["VR", "Gesture", "Wearables"],
    image: img("vpl-eyephone-demo.jpg"),
    span: 2,
  },
  {
    id: "virtuality",
    slug: "virtuality",
    wikiTitle: "Virtuality Arcade VR System",
    year: "1990",
    sortYear: 1990,
    title: "Virtuality",
    subtitle: "Networked VR in an arcade pod",
    blurb:
      "Amiga 3000s, camcorder LCDs, and magnetic tracking. Dactyl Nightmare let four players fight in cyberspace years before Doom.",
    tags: ["VR", "Arcade", "Multiplayer"],
    image: img("virtuality-1000cs-1.jpg"),
  },
  {
    id: "eyetap",
    slug: "eyetap",
    wikiTitle: "Steve Mann’s EyeTap / Wearable Computing",
    year: "1980s",
    sortYear: 1985,
    title: "EyeTap",
    subtitle: "Wearable computing before it had a name",
    blurb:
      "Steve Mann built camera-display eyeglasses in high school. The computer mediates reality itself — not a HUD, but a reversible eye.",
    tags: ["Wearable", "AR", "Sousveillance"],
    image: img("eyetap-mann-glass-2.jpg"),
  },
  {
    id: "digital-desk",
    slug: "digital-desk",
    wikiTitle: "The Digital Desk",
    year: "1991",
    sortYear: 1991,
    title: "The Digital Desk",
    subtitle: "Paper meets projector",
    blurb:
      "Pierre Wellner pointed a camera and projector at an ordinary desk. Point at printed numbers; the desk calculates and projects the answer onto the paper.",
    tags: ["Tangible", "AR", "Projection"],
    image: img("digital-desk-2.jpg"),
  },
  {
    id: "mandala",
    slug: "mandala",
    wikiTitle: "Mandala / The Vivid Group Gesture VR System",
    year: "1986",
    sortYear: 1986,
    title: "Mandala",
    subtitle: "Full-body VR on an Amiga",
    blurb:
      "The Vivid Group put your live video silhouette inside a virtual world. Punch objects, play drums, dance — 30fps, no controller, on an Amiga 1000.",
    tags: ["Gesture", "VR", "Computer Vision"],
    image: img("mandala-siggraph-1.jpg"),
  },
  {
    id: "put-that-there",
    slug: "put-that-there",
    wikiTitle: "Put-That-There",
    year: "1980",
    sortYear: 1980,
    title: "Put-That-There",
    subtitle: "Voice + gesture at the graphics interface",
    blurb:
      "MIT's Architecture Machine Group let you move shapes by speaking and pointing. It asked clarifying questions when it couldn't understand you.",
    tags: ["Voice", "Gesture", "Multimodal"],
    image: img("put-that-there-video.jpg"),
  },
  {
    id: "speak-spell",
    slug: "speak-spell",
    wikiTitle: "Texas Instruments Speak & Spell",
    year: "1978",
    sortYear: 1978,
    title: "Speak & Spell",
    subtitle: "The first talking chip",
    blurb:
      "Texas Instruments put a 10th-order LPC vocal tract model on a single chip. It taught kids to spell, became an IEEE Milestone, and soundtracked Kraftwerk.",
    tags: ["Voice", "Speech Synthesis", "Toy"],
    image: img("speak-spell-1.jpg"),
  },
  {
    id: "kurzweil",
    slug: "kurzweil-reading-machine",
    wikiTitle: "Kurzweil Reading Machine",
    year: "1976",
    sortYear: 1976,
    title: "Kurzweil Reading Machine",
    subtitle: "Print made audible for the blind",
    blurb:
      "The first omni-font OCR plus a CCD scanner plus a speech synthesizer. Walter Cronkite read his sign-off with it. Stevie Wonder took the first unit home.",
    tags: ["Accessibility", "OCR", "Text-to-Speech"],
    image: img("kurzweil-reading-machine-1.jpg"),
  },
  {
    id: "active-badge",
    slug: "active-badge",
    wikiTitle: "Olivetti Active Badge",
    year: "1992",
    sortYear: 1992,
    title: "Active Badge",
    subtitle: "Your location, broadcast every 10 seconds",
    blurb:
      "Olivetti Research made an IR badge that told the building where you were. Phones followed you. Desktops moved with you. Privacy was born as a question.",
    tags: ["Wearable", "Location-Aware", "Ubicomp"],
    image: img("active-badge-1.gif"),
  },
  {
    id: "twiddler",
    slug: "twiddler",
    wikiTitle: "Handykey Twiddler Chord Keyboard",
    year: "1992",
    sortYear: 1992,
    title: "Twiddler",
    subtitle: "A keyboard in one hand",
    blurb:
      "A chording keypad you hold like a grenade. MIT wearable researchers typed 60 wpm while walking. Still in production 33 years later.",
    tags: ["Input", "Chorded", "One-Handed"],
    image: img("twiddler-original-1.png"),
  },
  {
    id: "gridpad-100",
    slug: "gridpad-100",
    wikiTitle: "GRiDPad 100",
    year: "1989",
    sortYear: 1989,
    title: "GRiDPad 100",
    subtitle: "First commercial tablet computer with pen input.",
    blurb: "Pioneered portable form-factor handwriting recognition and stylus-driven UI on MS-DOS.",
    tags: ["pen computing", "handwriting recognition", "tablet PC"],
    image: img("gridpad-100-1.jpg"),
  },
  {
    id: "heathkit-hero-1",
    slug: "heathkit-hero-1",
    wikiTitle: "Heathkit HERO 1",
    year: "1982",
    sortYear: 1982,
    title: "Heathkit HERO 1",
    subtitle: "Educational robot with sonar, light, and sound sensors.",
    blurb: "Brought programmable physical-world sensing and locomotion to hobbyist HCI experiments.",
    tags: ["Educational Robot", "Programmable Sensing", "Human-Computer Interaction"],
    image: img("heathkit-hero-1-1.jpg"),
  },
  {
    id: "hp-150-touchscreen",
    slug: "hp-150-touchscreen",
    wikiTitle: "HP-150 Touchscreen",
    year: "1983",
    sortYear: 1983,
    title: "HP-150 Touchscreen",
    subtitle: "CRT monitor with infrared touch overlay for office PCs.",
    blurb: "First mass-market computer to ship with direct finger touch as primary input.",
    tags: ["Touchscreen", "Infrared touch", "MS-DOS computer"],
    image: img("hp-150-touchscreen-1.jpg"),
  },
  {
    id: "koalapad",
    slug: "koalapad",
    wikiTitle: "KoalaPad",
    year: "1984",
    sortYear: 1984,
    title: "KoalaPad",
    subtitle: "Pressure-sensitive touch tablet for 8-bit home computers.",
    blurb: "Brought absolute-position drawing and menu selection to consumer software years before mainstream mice.",
    tags: ["Graphics Tablet", "Touch Tablet", "Absolute Positioning"],
    image: img("koalapad-1.jpg"),
  },
  {
    id: "microwriter",
    slug: "microwriter",
    wikiTitle: "Microwriter",
    year: "1980",
    sortYear: 1980,
    title: "Microwriter",
    subtitle: "Five-key chorded portable word processor.",
    blurb: "Early wearable-style one-handed text entry device aimed at mobile professionals.",
    tags: ["chording keyboard", "portable computing", "mobile text entry"],
    image: img("microwriter-1.png"),
  },
  {
    id: "nintendo-d-pad-controller",
    slug: "nintendo-d-pad-controller",
    wikiTitle: "Nintendo D-pad controller",
    year: "1985",
    sortYear: 1985,
    title: "Nintendo D-pad controller",
    subtitle: "Cross-shaped directional pad replacing joysticks on consoles.",
    blurb: "Established the dominant discrete directional input paradigm still used in handheld and console gaming.",
    tags: ["D-pad", "Game controller", "NES"],
    image: img("nintendo-d-pad-controller-1.jpg"),
  },
  {
    id: "polhemus-isotrak",
    slug: "polhemus-isotrak",
    wikiTitle: "Polhemus 3Space Isotrak",
    year: "1987",
    sortYear: 1987,
    title: "Polhemus 3Space Isotrak",
    subtitle: "Magnetic 6DOF tracking sensor for 3D interaction.",
    blurb: "First widely available electromagnetic tracker enabling freehand spatial input in VR and CAD.",
    tags: ["6DOF Tracking", "Electromagnetic Tracking", "Virtual Reality"],
    image: img("polhemus-isotrak-1.png"),
  },
  {
    id: "poqet-pc",
    slug: "poqet-pc",
    wikiTitle: "Poqet PC",
    year: "1989",
    sortYear: 1989,
    title: "Poqet PC",
    subtitle: "Credit-card-sized MS-DOS computer with PCMCIA.",
    blurb: "Pushed the limits of portable full-PC interaction years before Palm and Windows CE.",
    tags: ["Palmtop PC", "Power Management", "MS-DOS"],
    image: img("poqet-pc-1.jpg"),
  },
  {
    id: "psion-organiser-ii",
    slug: "psion-organiser-ii",
    wikiTitle: "Psion Organiser II",
    year: "1986",
    sortYear: 1986,
    title: "Psion Organiser II",
    subtitle: "Pocket computer with full QWERTY and expansion slots.",
    blurb: "Early PDA that demonstrated mobile database and calculator interaction models.",
    tags: ["Personal Digital Assistant", "Mobile Database", "Calculator"],
    image: img("psion-organiser-ii-3.jpg"),
  },
  {
    id: "summagraphics-bit-pad",
    slug: "summagraphics-bit-pad",
    wikiTitle: "Summagraphics Bit Pad",
    year: "1977",
    sortYear: 1977,
    title: "Summagraphics Bit Pad",
    subtitle: "Large electromagnetic digitizing tablet for CAD.",
    blurb: "Standardized absolute coordinate input for professional graphics long before consumer tablets.",
    tags: ["Digitizing Tablet", "Absolute Positioning", "Professional Graphics"],
    image: img("summagraphics-bit-pad-1.jpg"),
  },
  {
    id: "writehander",
    slug: "writehander",
    wikiTitle: "WriteHander",
    year: "1978",
    sortYear: 1978,
    title: "WriteHander",
    subtitle: "Twelve-key one-handed chording keyboard for left or right hand.",
    blurb: "Early commercial attempt at compact, eyes-free chorded text entry that predates later wearable keyboards.",
    tags: ["Chorded Keyboard", "Wearable", "Eyes-Free"],
    image: img("writehander-1.jpg"),
  },
  {
    id: "fairlight-cmi",
    slug: "fairlight-cmi",
    wikiTitle: "Fairlight CMI (Computer Musical Instrument)",
    year: "1979",
    sortYear: 1979,
    title: "Fairlight CMI (Computer Musical Instrument)",
    subtitle: "The first digital sampling synthesizer — draw sound with a light pen.",
    blurb: "The first commercially successful creative tool that used a light pen for direct-manipulation content creation. Musicians drew sound waveforms on a CRT and composed visually via Page R, the first graphical pattern sequencer. Years before the Macintosh, it proved that visual, gestural interfaces could power professional creative work.",
    tags: ["Music HCI", "Light Pen", "Digital Audio"],
    image: img("fairlight-cmi-1.jpg"),
  },
  {
    id: "konami-laserscope",
    slug: "konami-laserscope",
    wikiTitle: "Konami LaserScope",
    year: "1990",
    sortYear: 1990,
    title: "Konami LaserScope",
    subtitle: "A voice-activated head-mounted targeting device for the NES — shout 'Fire!' to shoot.",
    blurb: "An astonishingly ambitious consumer wearable from 1990: head-mounted crosshair eyepiece + voice trigger + light gun sensor, all for $39.95. It combined head-based spatial aiming, voice input, heads-up display, and stereo headphones into a single NES peripheral. That it failed spectacularly — the mic triggered on any loud noise, neck fatigue from head-aiming, and you still needed a regular Zapper to make it work — makes it a perfect HCI design-failure case study.",
    tags: ["Voice Control", "Head-Mounted Display", "Gaming"],
    image: img("konami-laserscope-1.jpg"),
  },
  {
    id: "nes-power-pad",
    slug: "nes-power-pad",
    wikiTitle: "NES Power Pad (Family Trainer / Family Fun Fitness)",
    year: "1988",
    sortYear: 1988,
    title: "NES Power Pad (Family Trainer / Family Fun Fitness)",
    subtitle: "The first mass-market full-body exertion interface for home video games — run, jump, stomp.",
    blurb: "A foldable plastic floor mat with 12 pressure sensors that turned the player's entire body into a game controller. Years before DDR, Wii Fit, or Kinect, the Power Pad proved that feet and whole-body movement could be a viable consumer input modality. It pioneered exergaming, invented the 'body as controller' paradigm, and is the direct ancestor of every motion-based game interface that followed. Plus, kids discovered you could cheat by kneeling and slapping the mat with your hands.",
    tags: ["Full-Body Input", "Exergaming", "Floor Mat"],
    image: img("nes-power-pad-1.png"),
  },
  {
    id: "amiga-joyboard",
    slug: "amiga-joyboard",
    wikiTitle: "Amiga Joyboard",
    year: "1983",
    sortYear: 1983,
    title: "Amiga Joyboard",
    subtitle: "The world's first home-console balance board — a foot-operated Atari 2600 controller that gave us the 'Guru Meditation' error screen.",
    blurb: "Arguably the first commercial full-body input device for a home video game console, predating the Wii Balance Board by 23 years. A plastic board you stood on and leaned to control on-screen action, translating gross motor movement into digital directional input through simple mechanical latches.",
    tags: ["Balance Board", "Full-Body Interaction", "Game Controller"],
    image: img("amiga-joyboard-1.jpg"),
  },
  {
    id: "grope-iii",
    slug: "grope-iii",
    wikiTitle: "GROPE-III",
    year: "1990",
    sortYear: 1990,
    title: "GROPE-III",
    subtitle: "The first force-feedback molecular docking system that let chemists physically feel electrostatic forces between drug molecules and protein receptors.",
    blurb: "Repurposed a nuclear-industry teleoperator arm from Argonne National Lab as a 6-DOF haptic force display. Chemists grasped a handle and felt real-time electrostatic forces — steric repulsion, van der Waals attraction, and Coulomb forces — guiding drug molecules into protein receptor sites. Demonstrated a two-fold performance improvement over purely visual interaction and founded the field of haptic rendering.",
    tags: ["Haptics", "Force Feedback", "Scientific Visualization"],
    image: img("grope-iii-1.png"),
  },
  {
    id: "nintendo-hands-free",
    slug: "nintendo-hands-free",
    wikiTitle: "Nintendo Hands Free Controller",
    year: "1989",
    sortYear: 1989,
    title: "Nintendo Hands Free Controller",
    subtitle: "The first accessibility controller produced by a major gaming corporation, operated by chin and breath — 29 years ahead of its time.",
    blurb: "Designed for quadriplegic players and co-developed with Seattle Children's Hospital. A chest-strapped device with a chin-operated joystick for directional movement and a sip-and-puff tube: sipping activates A, puffing activates B. Sold at cost via mail-order with zero marketing, predating Microsoft's Xbox Adaptive Controller by 29 years. Very few units survive today.",
    tags: ["Accessibility", "Sip-and-Puff", "Assistive Technology"],
    image: img("nintendo-hands-free-1.jpg"),
  },
  {
    id: "dlr-spacemouse",
    slug: "dlr-spacemouse",
    wikiTitle: "DLR Control Ball (SpaceMouse)",
    year: "1981",
    sortYear: 1981,
    title: "DLR Control Ball",
    subtitle: "The first 6-DOF force-sensing ball: push, twist, and pull your way through 3D space — built for robots, launched in orbit, and still on desks today",
    blurb: "A tennis-ball-sized sphere that reads minute hand pressures — not position, not movement, but force — and translates them into simultaneous control of all six degrees of freedom. Developed at the German Aerospace Center in 1981. Used on Space Shuttle Columbia. Still in production as the 3Dconnexion SpaceMouse.",
    tags: ["6-DOF Input", "Force Input", "Spatial Controller"],
    image: img("dlr-spacemouse-2.jpg"),
  },
  {
    id: "dragondictate",
    slug: "dragondictate",
    wikiTitle: "DragonDictate",
    year: "1989",
    sortYear: 1989,
    title: "DragonDictate",
    subtitle: "The first large-vocabulary speech-to-text dictation: 30,000 words, one $9,000 DSP board, and an 'Oops' command",
    blurb: "Dragon Systems' husband-wife team put 30,000-word speech recognition on a 386 PC with a $9,000 ISA DSP board and Shure headset. Defined the dictation interaction model: speak, pause, 'Oops' to correct. Life-changing for quadriplegic users.",
    tags: ["Speech Recognition", "Dictation", "Natural Language"],
    image: img("dragondictate-1.png"),
  },
  {
    id: "eyetyper",
    slug: "eyetyper",
    wikiTitle: "EyeTyper",
    year: "1983",
    sortYear: 1983,
    title: "EyeTyper",
    subtitle: "The first camera-based eye-typing device: look to type, dwell to select",
    blurb: "A video camera pointed at one eyeball. A display board with oversized characters. Hold your gaze — and type at 10 words per minute. CMU spinoff Sentient Systems launched EyeTyper in 1983; the company became DynaVox, then Tobii Dynavox.",
    tags: ["Eye-Tracking", "Accessibility", "Camera-Based Input"],
    image: img("eyetyper-1.png"),
  },
  {
    id: "biomuse",
    slug: "biomuse",
    wikiTitle: "BioMuse",
    year: "1990",
    sortYear: 1990,
    title: "BioMuse",
    subtitle: "The first commercial biosignal controller: muscle tension, eye movement, and brainwaves become music",
    blurb: "Eight channels of EMG, EOG, and EEG electrodes feed a $20,000 DSP box. Tensing a forearm muscle triggers a synth note. Shifting your gaze bends a parameter. Built at Stanford's CCRMA by Hugh Lusted and Benjamin Knapp in 1990. Performed in concert halls by Atau Tanaka. Used by NASA, the U.S. Air Force, and a disabled child playing video games at Loma Linda Medical Center.",
    tags: ["Biosignals", "Music", "Accessibility", "Wearable", "EMG"],
    image: img("biomuse/biomuse-system.jpg"),
  },
  {
    id: "etak-navigator",
    slug: "etak-navigator",
    wikiTitle: "Etak Navigator",
    year: "1985",
    sortYear: 1985,
    title: "Etak Navigator",
    subtitle: "The first practical in-car navigation computer, using dead reckoning and a rotating map — years before GPS",
    blurb: "A shoebox-sized 8088 computer in the trunk, a compass on the rear windshield, wheel sensors on the brakes, and maps on high-speed cassette tapes. No GPS — just dead reckoning and a map-matching algorithm that snapped your position to the nearest road. Nolan Bushnell seed-funded it after a 4am yacht conversation. Its heading-up rotating map display and triangular arrow symbol became the universal standard for every navigation app since.",
    tags: ["Navigation", "Automotive", "Map Display", "Location"],
    image: img("etak-navigator/etak-popsci.jpg"),
  },
  {
    id: "nintendo-rob",
    slug: "nintendo-rob",
    wikiTitle: "Nintendo R.O.B. (Robotic Operating Buddy)",
    year: "1985",
    sortYear: 1985,
    title: "Nintendo R.O.B.",
    subtitle: "A physical robot companion that played NES games with you, commanded by light flashes from the TV screen",
    blurb: "R.O.B. is an output device disguised as a friend. The NES draws flashing green and black rectangles on a CRT screen. A phototransistor in R.O.B.'s head decodes the pulses into motor commands. Three DC motors grind into action, and the robot reaches into the real world to press buttons on a second controller. Designed by Gunpei Yokoi. Discontinued by 1988. But before that, it saved Nintendo — retailers wouldn't stock a 'video game console' after the 1983 crash, so they bundled a robot and called it a toy.",
    tags: ["Robotics", "Game Peripheral", "Physical Computing", "Embodied Interaction"],
    image: img("nintendo-rob/rob-studio.jpg"),
  },
  {
    id: "private-eye",
    slug: "private-eye",
    wikiTitle: "Private Eye",
    year: "1989",
    sortYear: 1989,
    title: "Private Eye",
    subtitle: "The vibrating-mirror monocular display that launched wearable computing and became the Nintendo Virtual Boy",
    blurb: "A 2.5-ounce monochrome display using 280 LEDs and a vibrating mirror to paint a 720x280 image onto your retina. By covering only one eye, your brain fused the display with reality — accidental AR, years before the term existed. MIT researchers wore them daily. Google Glass traces its lineage here.",
    tags: ["Head-Mounted Display", "Wearable", "Augmented Reality"],
    image: img("private-eye/pe-display-unit.png"),
  },
  {
    id: "radio-drum",
    slug: "radio-drum",
    wikiTitle: "Radio Drum / Radio Baton",
    year: "c.1987",
    sortYear: 1987,
    title: "Radio Drum",
    subtitle: "A 3D capacitive spatial controller that tracks two batons in free space — built as a mouse, reborn as an instrument",
    blurb: "Max Mathews, father of computer music, and Bell Labs engineer Bob Boie built a 3D mouse that failed. Then they realized it was a musical instrument. Two batons hover above a capacitance-sensing antenna plate, tracking X, Y, and Z at 100Hz with 1mm precision. No contact required.",
    tags: ["3D Spatial Input", "Music HCI", "Gestural Controller"],
    image: img("radio-drum/rd-ccrma-device.jpg"),
  },
  {
    id: "uforce",
    slug: "uforce",
    wikiTitle: "Broderbund U-Force",
    year: "1989",
    sortYear: 1989,
    title: "U-Force",
    subtitle: "The NES touchless controller with the unfortunate slogan 'Don't Touch!' — nine infrared beams, zero playability, one magnificent failure",
    blurb: "Broderbund Software had never made hardware. Then it shipped a clamshell pad with nine IR emitter-detector pairs that tracked your hand in 3D space above the NES. Ambient light confused it. Calibration drifted. 'Don't Touch!' became an ironic epitaph. A perfect HCI failure study.",
    tags: ["Touchless Input", "Infrared Sensing", "Gaming"],
    image: img("uforce/uf-wikipedia.jpg"),
  },
  {
    id: "fakespeare-boom",
    slug: "fakespeare-boom",
    wikiTitle: "Fakespeare BOOM (Binocular Omni-Orientation Monitor)",
    year: "1989",
    sortYear: 1989,
    title: "Fakespeare BOOM",
    subtitle: "Press your face against a CRT on a counterbalanced mechanical arm — immersive VR with zero latency, zero weight on your head",
    blurb: "Suspended two 1280x1024 CRTs and LEEP optics inside a viewing hood on a spring-balanced articulated arm. Gripped the handles, pressed your face in, and physically wrestled the display through space — joint encoders giving sub-millisecond 6-DOF tracking. Invented by Mark Bolas (who later mentored Oculus founder Palmer Luckey). Used by NASA, Boeing, and Sandia Labs.",
    tags: ["VR", "Immersive Display", "Head-Coupled Display"],
    image: img("fakespeare-boom-1.gif"),
  },
  {
    id: "buchla-lightning",
    slug: "buchla-lightning",
    wikiTitle: "Buchla Lightning",
    year: "1991",
    sortYear: 1991,
    title: "Buchla Lightning",
    subtitle: "Conjure music from thin air — two infrared wands, one optical tracker, and a DSP that reads your gestures as MIDI",
    blurb: "Don Buchla built an optical gesture-sensing MIDI controller 15 years before the Wii. Two wireless wands emit IR light; a photosensor array triangulates their position, velocity, and acceleration in real time. A TMS370 DSP classifies strikes, sweeps, and zones into MIDI notes and controllers. $1,995, hand-built in Berkeley. Used at IRCAM, CCRMA, and Times Square's millennium celebration.",
    tags: ["Music HCI", "Gesture", "Optical Tracking"],
    image: img("buchla-lightning-1.jpg"),
  },
  {
    id: "seiko-rc1000",
    slug: "seiko-rc1000",
    wikiTitle: "Seiko RC-1000 Wrist Terminal",
    year: "1984",
    sortYear: 1984,
    title: "Seiko RC-1000 Wrist Terminal",
    subtitle: "A wristwatch that plugs into your desktop computer — the first wrist-worn computer terminal, a decade ahead of its time",
    blurb: "The same year the Macintosh shipped, Seiko sold a wristwatch with 2KB RAM, a 12x2 dot-matrix LCD, and an RS-232C serial port. You authored data on a desktop PC, then blasted it to the watch in a 2051-byte dump. Read-only on the wrist. Spawned the WristMac, which flew on Space Shuttle Atlantis in 1991 for the first email from space.",
    tags: ["Wearable", "Wrist-Worn", "Mobile Computing"],
    image: img("seiko-rc1000-1.jpg"),
  },
  {
    id: "barcode-battler",
    slug: "barcode-battler",
    wikiTitle: "Barcode Battler / バーコードバトラー",
    year: "1991",
    sortYear: 1991,
    title: "Barcode Battler",
    subtitle: "A handheld game that turned every supermarket barcode into an RPG character — Japan's brief, glorious fad for scanning cereal boxes into warriors",
    blurb: "In 1991, Epoch Co. released a handheld LCD game with a built-in barcode scanner. Swipe any product barcode through its slot — cereal, soup, toilet paper — and an algorithm hashed the digits into character stats for turn-based RPG combat. No graphics, just 7-segment numbers. In Japan, it was a mania: products sold out because kids thought they had lucky barcodes. In the West, it flopped completely. A genuinely novel physical-to-digital bridge, decades before Skylanders or QR-code games.",
    tags: ["Barcode", "Tangible", "Gaming"],
    image: img("barcode-battler-1.png"),
  },
  {
    id: "kramers-talking-glove",
    slug: "kramers-talking-glove",
    wikiTitle: "Talking Glove / The TalkingGlove",
    year: "1988",
    sortYear: 1988,
    title: "Talking Glove",
    subtitle: "A glove that translated American Sign Language fingerspelling into spoken words in real time",
    blurb: "The first portable ASL-to-speech translation system: 14 strain-gauge flex sensors, a beacon recognition algorithm in 16-dimensional hand-space, and a DECtalk speech synthesizer. Built by James Kramer at Stanford (1988–1991) for deaf users to have everyday conversations without an interpreter. The sensor design proved so robust it became the CyberGlove, dominating VR hand-input for two decades before Immersion Corp acquired it and leveraged the patents against Microsoft and Sony.",
    tags: ["Wearable", "Accessibility", "Gesture Recognition"],
    image: img("kramers-talking-glove-1.png"),
  },
  {
    id: "williams-facial-animation",
    slug: "williams-facial-animation",
    wikiTitle: "Performance-Driven Facial Animation",
    year: "1990",
    sortYear: 1990,
    title: "Performance-Driven Facial Animation",
    subtitle: "The first system to use a live actor's real face as a real-time input device for computer-generated animation",
    blurb: "At SIGGRAPH 1990, Lance Williams of Apple ATG introduced the 'electronic mask': retroreflective dots on an actor's face tracked by computer vision, driving a photorealistic 3D CG character in real time. The actor's smile, frown, or raised eyebrow became a real-time animation input stream — the birth of facial performance capture, decades before Avatar or ARKit. Williams later served as Chief Scientist at Walt Disney Animation Studios and won a Technical Academy Award for this work.",
    tags: ["Facial Tracking", "Computer Vision", "Performance Capture"],
    image: img("williams-facial-animation-1.jpg"),
  },
  {
    id: "convolvotron",
    slug: "convolvotron",
    wikiTitle: "Convolvotron",
    year: "1988",
    sortYear: 1988,
    title: "Convolvotron",
    subtitle: "The first real-time 3D audio spatializer — a $15,000 PC board set from NASA's VIEW lab that let you listen through someone else's ears",
    blurb: "Built under a NASA contract by Scott Foster and Crystal River Engineering, the Convolvotron was the first system capable of real-time binaural spatialization of multiple independent sound sources. A custom parallel ALU engine with 128 16×16 multiply-accumulators performed head-related transfer function (HRTF) convolution in real time — as you turned your head, virtual sound sources stayed anchored in 3D space through standard stereo headphones. At $14,995 for a two-board PC set, it spawned a product family (Acoustetron, Beachtron, Alphatron) and was used in landmark VR artworks including Brenda Laurel's Placeholder and Char Davies' Osmose. Its technology was distilled into Aureal's A3D consumer 3D audio API before being acquired by Creative Technology.",
    tags: ["Audio", "Spatial Audio", "VR", "NASA"],
    image: img("convolvotron-1.jpg"),
  },
  {
    id: "headmaster",
    slug: "headmaster",
    wikiTitle: "HeadMaster",
    year: "1986",
    sortYear: 1986,
    title: "HeadMaster",
    subtitle: "An ultrasonic headset that turned head movement into cursor movement — 'If you can move your head, you can move your world'",
    blurb: "The first commercially successful head-operated computer cursor controller. A lightweight headset with three 40 kHz ultrasonic receivers tracked rotational head movement (yaw and pitch) through analog phase-comparison circuitry, sampled at 1,000 Hz with sub-millimeter resolution. A sip-and-puff mouth switch provided mouse-button clicks. Built by Personics Corp in 1986 for $795, later sold by Prentke Romich Company through the 2000s, it came with ScreenTyper — an on-screen keyboard with characters arranged by frequency of use, a decade before soft keyboards became common. Its patent was classified under G06F3/012 'Head tracking input arrangements' — the same classification that would define VR input. Units are held by both the Smithsonian and the Computer History Museum.",
    tags: ["Head Tracking", "Accessibility", "Ultrasonic", "Cursor Control"],
    image: img("headmaster-1.png"),
  },
  {
    id: "vpl-datasuit",
    slug: "vpl-datasuit",
    wikiTitle: "VPL DataSuit",
    year: "1989",
    sortYear: 1989,
    title: "VPL DataSuit",
    subtitle: "The first full-body fiber-optic tracking suit — 30+ sensors across arms, legs, and trunk, your entire body as computer input",
    blurb: "The VPL DataSuit extended the DataGlove's fiber-optic bend sensor technology from one hand to the entire body. Worn as a tight Lycra outfit with 30+ sensors measuring joint angles along arms, legs, and trunk, it made the human body a real-time input device for virtual environments. Combined with the EyePhone HMD and DataGlove in VPL's 'Reality Built for Two' (RB2) — the first multi-user VR system — it embodied Jaron Lanier's concept of 'post-symbolic communication': using body movement as a programming language. Ann Lasko-Harvill designed gender-specific tailoring for different body types. The suit appeared in the 1992 film The Lawnmower Man, introducing full-body VR to mass audiences. Though VPL filed for bankruptcy in 1990, the DataSuit established the template for every full-body tracking system that followed.",
    tags: ["VR", "Wearable", "Motion Capture", "Full-Body"],
    image: img("vpl-datasuit-1.jpg"),
  },
  {
    id: "minsky-sandpaper",
    slug: "minsky-sandpaper",
    wikiTitle: "Minsky Sandpaper / Computational Haptics Sandpaper System",
    year: "1990",
    sortYear: 1990,
    title: "Minsky Sandpaper",
    subtitle: "The 2-DOF force-feedback joystick that synthesized virtual textures through programmable lateral forces, birthing computational haptics.",
    blurb: "The origin story of computational haptics — the moment touch became programmable. Margaret Minsky's 2-DOF force-feedback joystick used a lateral-force algorithm to synthesize virtual textures (sandpaper, rubber, velvet) that users could genuinely feel and distinguish. A wooden box with DC motors, optical encoders, and metal linkages — every haptic device since descends from it.",
    tags: ["Haptics", "Force Feedback", "MIT Media Lab"],
    image: img("minsky-sandpaper-1.webp"),
  },
  {
    id: "quantel-paintbox",
    slug: "quantel-paintbox",
    wikiTitle: "Quantel Paintbox",
    year: "1981",
    sortYear: 1981,
    title: "Quantel Paintbox",
    subtitle: "The $250,000 broadcast graphics workstation that put a pressure-sensitive stylus in the hands of TV artists and defined the look of 1980s television.",
    blurb: "The first computer graphics system designed as an artist's tool rather than an engineer's. Its patented pressure-sensitive stylus and tablet, combined with real-time pop-up menus, let traditionally trained illustrators produce broadcast-quality digital graphics with zero computer knowledge. A decade before consumer tablets and Photoshop, it proved natural gestural interaction could power professional creative work.",
    tags: ["Graphics HCI", "Pressure-Sensitive Stylus", "Broadcast Graphics"],
    image: img("quantel-paintbox-1.jpg"),
  },
  {
    id: "tongue-touch-keypad",
    slug: "tongue-touch-keypad",
    wikiTitle: "Tongue Touch Keypad (TTK) / Tongue Activated Communications Controller",
    year: "1991",
    sortYear: 1991,
    title: "Tongue Touch Keypad",
    subtitle: "The intraoral dental retainer with a nine-key membrane keypad that let quadriplegics control computers by touching their tongue to the roof of their mouth.",
    blurb: "A custom-fitted dental retainer embedding a nine-key keypad, digital encoder, and magnetic-flux radio transmitter — worn on the palate and operated entirely by tongue. Received FDA clearance in 1991, served ~70 quadriplegic users, and established the paradigm for every modern intraoral interface from the Georgia Tech Tongue Drive to MIT's MouthIO.",
    tags: ["Accessibility", "Assistive Technology", "Tongue Interface"],
    image: img("tongue-touch-keypad-1.png"),
  },
  {
    id: "aesthedes",
    slug: "aesthedes",
    wikiTitle: "Aesthedes",
    year: "1984",
    sortYear: 1984,
    title: "Aesthedes",
    subtitle: "The 220 kg Dutch design workstation with 636 dedicated membrane keys, six screens, and a philosophy that designers should never need to learn computers.",
    blurb: "A dedicated graphic-design workstation where every function had a physical key spread across the desk surface — 583 membrane switches on the Aesthedes 1, 636 on the Aesthedes 2. Six screens (three colour, three monochrome) gave every view its own monitor. Ten Motorola 68000 CPUs, 220 kg, and a price tag of $150,000. It designed Dutch banknotes, Heineken labels, and Volvo dashboards before the Macintosh killed it.",
    tags: ["CAD", "Workstation", "Keyboard"],
    image: img("aesthedes-1.jpg"),
  },
  {
    id: "rdi-halcyon",
    slug: "rdi-halcyon",
    wikiTitle: "RDI Halcyon",
    year: "1985",
    sortYear: 1985,
    title: "RDI Halcyon",
    subtitle: "The voice-controlled laserdisc game console that trained itself to your voice, cost $2,500, and sold perhaps ten units before vanishing into legend.",
    blurb: "A consumer device in 1985 that bet its entire identity on speech recognition. No joystick, no keyboard — you talked to it through a noise-canceling headset while it navigated branching laserdisc movies with your spoken commands. Funded by Dragon's Lair profits, killed by the 1983 game crash and a price tag that bought 14 NES consoles. One of the rarest game consoles ever made.",
    tags: ["Gaming", "Voice Recognition", "Laserdisc"],
    image: img("rdi-halcyon-1.jpg"),
  },
  {
    id: "talking-signs",
    slug: "talking-signs",
    wikiTitle: "Talking Signs / Remote Infrared Audible Signage (RIAS)",
    year: "1979",
    sortYear: 1979,
    title: "Talking Signs",
    subtitle: "The invisible city: infrared beams broadcasting spoken directions that only you can hear, turning the built environment into an ambient interface for blind navigation.",
    blurb: "A network of infrared transmitters that broadcast spoken labels on modulated light beams. A blind person carrying a pocket receiver could 'read' the city by pointing it around — doorways, bus stops, ATMs would whisper their names with directional clarity. Codified into US federal building standards (ADAAG 703.7) in 2000. In 2016, the concept became a free smartphone app used by thousands daily.",
    tags: ["Accessibility", "Infrared", "Navigation"],
    image: img("talking-signs-1.jpg"),
  },
  {
    id: "canon-cat",
    slug: "canon-cat",
    wikiTitle: "Canon Cat",
    year: "1987",
    sortYear: 1987,
    title: "Canon Cat",
    subtitle: "Jef Raskin's radical text-centric computer that rejected files, applications, and the mouse.",
    blurb: "No files, no applications, no operating system — just a single unified document stream navigated by content via pink LEAP keys. Designed by the man who initiated the Macintosh, it represents the road not taken in personal computing. The interaction model IS the point.",
    tags: ["HCI", "Input", "Interface Paradigm"],
    image: img("canon-cat-1.jpg"),
  },
  {
    id: "puma-rs-computer-shoes",
    slug: "puma-rs-computer-shoes",
    wikiTitle: "Puma RS Computer Shoes",
    year: "1985",
    sortYear: 1985,
    title: "Puma RS Computer Shoes",
    subtitle: "The first body-worn computer activity tracker — a running shoe you plugged into your Apple IIe.",
    blurb: "The PUMA RS-Computer transformed a shoe into an active sensing peripheral, measuring stride timing to compute distance, speed, and calories. After a run, you physically plugged your shoes into a computer's printer port to download data — a ritual that anticipated every fitness wearable by 20 years.",
    tags: ["HCI", "Wearable", "Sensing"],
    image: img("puma-rs-computer-shoes-1.jpg"),
  },
  {
    id: "versabraille",
    slug: "versabraille",
    wikiTitle: "VersaBraille",
    year: "1979",
    sortYear: 1979,
    title: "VersaBraille",
    subtitle: "The first American refreshable Braille display, turning screen text into raised dots under the fingers.",
    blurb: "A 20-cell piezoelectric Braille display that functioned as notetaker, reading machine, and computer terminal — giving blind users direct tactile access to electronic text for the first time. The same transducer technology invented for this device still powers most Braille displays today.",
    tags: ["HCI", "Accessibility", "Tactile"],
    image: img("versabraille-1.jpg"),
  },
  {
    id: "mbx-expansion-system",
    slug: "mbx-expansion-system",
    wikiTitle: "MBX Expansion System",
    year: "1983",
    sortYear: 1983,
    title: "MBX Expansion System",
    subtitle: "Consumer voice-recognition gaming peripheral that trained on your voice, then let you shout commands at the screen.",
    blurb: "In 1983, Milton Bradley shipped a peripheral that wore a headset, learned your voice, understood spoken game commands, and paired them with a 360-degree analog joystick with a twist knob and a 64-key membrane overlay keypad. Voice-recognition gaming in 1983.",
    tags: ["HCI", "Input", "Voice"],
    image: img("mbx-expansion-system-1.jpg"),
  },
  {
    id: "drawing-prism",
    slug: "drawing-prism",
    wikiTitle: "The Drawing Prism",
    year: "1985",
    sortYear: 1985,
    title: "The Drawing Prism",
    subtitle: "An optical bridge between real brushes and digital pixels — paint directly into a computer with your hands.",
    blurb: "A transparent glass prism that let artists paint with real brushes, fingers, or any light-colored object directly into a computer's frame buffer in 1985. A video camera underneath saw only points of optical contact via frustrated total internal reflection.",
    tags: ["HCI", "Input", "Art"],
    image: img("drawing-prism-1.jpg"),
  },
  {
    id: "datahand-keyboard",
    slug: "datahand-keyboard",
    wikiTitle: "DataHand Keyboard",
    year: "1990",
    sortYear: 1990,
    title: "DataHand Keyboard",
    subtitle: "The keyboard where your fingers never move — each digit rests in a padded well and types by twitching in five directions.",
    blurb: "The most extreme keyboard redesign ever brought to market. Each finger rests in a padded well with five magnetic switches (N/S/E/W + center). No wrist movement, sub-millimeter finger twitches. Invented by Dale Retter to solve his own RSI, prototyped by 1989, sold from 1990.",
    tags: ["HCI", "Input", "Ergonomic"],
    image: img("datahand-keyboard-1.jpg"),
  },
  {
    id: "pencept-penpad",
    slug: "pencept-penpad",
    wikiTitle: "Pencept PenPad",
    year: "1982",
    sortYear: 1982,
    title: "Pencept PenPad",
    subtitle: "A keyboardless terminal that read your handwriting—and your gestures—in 1982",
    blurb: "A terminal replacement with no keyboard—just a pen and tablet. Used MIT-developed user-independent handwriting recognition and gesture commands (circle to select, scribble to delete). CHI '85 demo showed real-time pen computing a decade before the Newton.",
    tags: ["Pen Computing", "Handwriting Recognition", "Gesture"],
    image: img("pencept-penpad-1.jpg"),
  },
  {
    id: "relax-stress-reduction",
    slug: "relax-stress-reduction",
    wikiTitle: "Synapse Relax Stress Reduction System",
    year: "1984",
    sortYear: 1984,
    title: "Synapse Relax Stress Reduction System",
    subtitle: "A video-game company built the first FDA-cleared biofeedback peripheral for home computers—and it almost worked",
    blurb: "An EMG headband, control unit, and software that let you fly a balloon by relaxing. Synapse Software (of Blue Max fame) got FDA clearance as a Class II medical device in 1984. Co-created by legendary game designer Bill Williams. Rarity 9 on AtariMania.",
    tags: ["Biofeedback", "Physiological Computing", "Wearable"],
    image: img("relax-stress-reduction-1.png"),
  },
  {
    id: "exciting-boxing",
    slug: "exciting-boxing",
    wikiTitle: "Exciting Boxing Controller",
    year: "1987",
    sortYear: 1987,
    title: "Exciting Boxing Controller",
    subtitle: "An inflatable humanoid punching bag you physically fought to control a Famicom boxing game",
    blurb: "An inflatable, life-sized boxer with 11 internal pressure sensors that plugged into the Nintendo Famicom. You stood on a mat, put on knitted gloves, and physically punched the bag. Konami, 1987. Full-body motion gaming nearly two decades before the Wii.",
    tags: ["Game Controller", "Full-Body Input", "Motion Gaming", "Famicom"],
    image: img("exciting-boxing-1.jpg"),
  },
  {
    id: "ibva",
    slug: "ibva",
    wikiTitle: "Interactive Brainwave Visual Analyzer (IBVA)",
    year: "1991",
    sortYear: 1991,
    title: "Interactive Brainwave Visual Analyzer (IBVA)",
    subtitle: "The first commercial wireless brain-computer interface — think with your forehead, control a Mac with your mind",
    blurb: "A wireless EEG headband that transmitted brainwaves by radio to a Macintosh, converting alpha and beta rhythms into MIDI notes, visuals, and control signals. Shipped April 1991 by Psychic Lab Inc. Used by Mariko Mori at the Venice Biennale, and by HBO to measure TV audience engagement.",
    tags: ["BCI", "EEG", "Wearable", "Brainwave"],
    image: img("ibva-5.jpg"),
  },
  {
    id: "cave",
    slug: "cave",
    wikiTitle: "CAVE Automatic Virtual Environment",
    year: "1992",
    sortYear: 1992,
    title: "CAVE Automatic Virtual Environment",
    subtitle: "The first room-scale VR — no headset, just a room you walked into",
    blurb: "The CAVE turned the room itself into the display: three walls and a floor projecting stereoscopic 3D that surrounded you, rendered from your tracked viewpoint. You walked naturally. Three other people could stand in there with you, making eye contact and pointing at the same virtual objects.",
    tags: ["VR", "Immersive", "Display"],
    image: img("cave-1.jpg"),
  },
  {
    id: "virtual-fixtures",
    slug: "virtual-fixtures",
    wikiTitle: "Virtual Fixtures",
    year: "1992",
    sortYear: 1992,
    title: "Virtual Fixtures",
    subtitle: "The first augmented reality system — a full upper-body exoskeleton that let you see and feel virtual objects registered in the real world",
    blurb: "In 1992, Louis Rosenberg bolted himself into a full upper-body exoskeleton covered in motors, peered through binocular magnifiers salvaged from a parachute test rig, and reached out to touch a virtual surface that pushed back — the first system to merge real and virtual with force feedback.",
    tags: ["Augmented Reality", "Haptic", "Exoskeleton"],
    image: img("virtual-fixtures-1.jpg"),
  },
  {
    id: "vectrex-3d-imager",
    slug: "vectrex-3d-imager",
    wikiTitle: "Vectrex 3D Imager",
    year: "1983",
    sortYear: 1983,
    title: "Vectrex 3D Imager",
    subtitle: "Color 3D from a black-and-white screen — using a motorized spinning filter disk strapped to your face",
    blurb: "The first commercially released stereoscopic 3D gaming peripheral: a headset with a spinning half-black, half-RGB filter disk synced to the Vectrex vector CRT via PWM motor control. Only ~2,000 units escaped before the 1983 crash. Invented by John Ross, who also created the Vectrex itself.",
    tags: ["3D Display", "Gaming", "Electromechanical", "Stereoscopic"],
    image: img("vectrex-3d-imager.jpg"),
  },
  {
    id: "soundbeam",
    slug: "soundbeam",
    wikiTitle: "Soundbeam",
    year: "1984",
    sortYear: 1984,
    title: "Soundbeam",
    subtitle: "The invisible keyboard in space — ultrasonic sonar that turned body movement into music, then accidentally revolutionized disability music therapy",
    blurb: "Touch-free MIDI controller using 50 kHz sonar beams. Conceived by composer Edward Williams, built by the EMS team (legendary VCS3 synth). Dancers were supposed to use it. Instead, children with profound disabilities made music for the first time. Still in production in 2025.",
    tags: ["Sonar", "Music", "MIDI", "Gestural", "Accessibility", "Embodied"],
    image: img("soundbeam-system.jpg"),
  },
  {
    id: "hard-drivin",
    slug: "hard-drivin",
    wikiTitle: "Hard Drivin' / Race Drivin'",
    year: "1989",
    sortYear: 1989,
    title: "Hard Drivin'",
    subtitle: "The arcade machine that strapped a real DC motor to your steering wheel — and hid a Milliken-level vehicle physics model inside",
    blurb: "First commercial arcade game with continuous force-feedback steering (not vibration — actual road-force resistance). Full manual transmission with clutch and H-pattern shifter. Real vehicle dynamics by Doug Milliken, credited as 'test driver' to keep it secret. 3,318 cabinets built. Every modern force-feedback racing wheel descends from this.",
    tags: ["Force Feedback", "Haptics", "Arcade", "Simulation"],
    image: img("hard-drivin-flyer.jpg"),
  },
  {
    id: "cauzin-softstrip",
    slug: "cauzin-softstrip",
    wikiTitle: "Cauzin Softstrip Reader",
    year: "1985",
    sortYear: 1985,
    title: "Cauzin Softstrip Reader",
    subtitle: "Before QR codes, this $200 wand turned magazine pages into computer data—one manual 30-second swipe at a time.",
    blurb: "The Cauzin Softstrip is the most literal 'paper-to-silicon bridge' ever sold as a consumer computer peripheral. You physically dragged this beige wand over a strip of tiny black-and-white squares printed in Byte magazine, and 5,500 bytes of program code materialized on your Apple II. Co-founder Jack Goldman had founded Xerox PARC. It won MacUser's 'Most Innovative Concept of 1986' and died within three years, outrun by floppy disks and modems.",
    tags: ["Input", "Scanning", "Optical Reader"],
    image: img("cauzin-softstrip-1.jpeg"),
  },
  {
    id: "reading-epg",
    slug: "reading-epg",
    wikiTitle: "Reading Electropalatography (EPG) System",
    year: "1978",
    sortYear: 1978,
    title: "Reading Electropalatography System",
    subtitle: "A computer worn inside the mouth—62 gold electrodes on a custom acrylic palate turned invisible tongue movements into a real-time visual targeting game.",
    blurb: "One of the most intimate human-computer interfaces ever built. A custom-molded acrylic plate, clipped to the user's upper teeth like a retainer, carries 62 gold electrodes in an 8-row grid. When the tongue touches the palate during speech, a CRT monitor illuminates dots wherever contact occurs—turning the invisible act of articulation into a visible, teachable skill. Developed at the University of Reading in 1978.",
    tags: ["Biofeedback", "Speech Therapy", "Accessibility"],
    image: img("reading-epg-1.jpg"),
  },
];

export const exhibits: Exhibit[] = exhibitData.toSorted((a, b) => b.sortYear - a.sortYear || a.title.localeCompare(b.title));
export const exhibitsByNewestAdded: Exhibit[] = exhibitData.toReversed();

export const featured = exhibits.find((e) => e.feature) ?? exhibits[0]!;
